locals {
  modecissions_app_secret_names = toset([
    "ANTHROPIC_API_KEY",
    "GEMINI_API_KEY",
    "JWT_SECRET_KEY",
    "INTERNAL_API_KEY",
    "INTERNAL_API_KEY_CONSOLE_TO_CONSOLE",
    "INTERNAL_API_KEY_CONSOLE_TO_REFINEMENT",
    "INTERNAL_API_KEY_CONSOLE_TO_VAULT",
    "INTERNAL_API_KEY_CONSOLE_TO_MCP_INFRA",
    "INTERNAL_API_KEY_CONSOLE_TO_CARTRIDGE",
    "INTERNAL_API_KEY_AIRFLOW_TO_CARTRIDGE",
    "INTERNAL_API_KEY_WORKSPACE_TO_CONSOLE",
    "INTERNAL_API_KEY_WORKSPACE_TO_REFINEMENT",
    "INTERNAL_API_KEY_WORKSPACE_TO_MCP_INFRA",
    "INTERNAL_API_KEY_AIRFLOW_TO_MCP_INFRA",
    "INTERNAL_API_KEY_AIRFLOW_TO_REFINEMENT",
    "INTERNAL_API_KEY_AIRFLOW_TO_CONSOLE",
    "INTERNAL_API_KEY_REFINEMENT_TO_MCP_INFRA",
    "INTERNAL_API_KEY_REPLICON_TO_CONSOLE",
    "INTERNAL_API_KEY_REPLICON_TO_MCP_INFRA",
    "INTERNAL_API_KEY_REPLICON_TO_REFINEMENT",
    "INTERNAL_API_KEY_HUBSPOT_TO_CONSOLE",
    "INTERNAL_API_KEY_HUBSPOT_TO_MCP_INFRA",
    "INTERNAL_API_KEY_HUBSPOT_TO_REFINEMENT",
    "INTERNAL_API_KEY_SALESFORCE_TO_CONSOLE",
    "INTERNAL_API_KEY_SAP_HCM_TO_CONSOLE",
    "INTERNAL_API_KEY_SAP_S4HANA_TO_CONSOLE",
    "INTERNAL_API_KEY_SAP_SUCCESSFACTORS_TO_CONSOLE",
    "INTERNAL_API_KEY_MCP_INFRA_TO_VAULT",
    "INTERNAL_API_KEY_CARTRIDGE_TO_CONSOLE",
    "INTERNAL_API_KEY_CARTRIDGE_TO_REFINEMENT",
    "INTERNAL_API_KEY_WORKSPACE_TO_VAULT",
    "INTERNAL_API_KEY_REFINEMENT_TO_VAULT",
    "POSTGRES_PASSWORD",
    "FIELD_ENCRYPTION_KEY",
    "VAULT_ENCRYPTION_KEY",
    "SMTP_PASSWORD",
    "OMEGA_CONSOLE_PASSWORD",
    "OMEGA_REFINEMENT_PASSWORD",
    "OMEGA_VAULT_PASSWORD",
    "OMEGA_WORKSPACE_PASSWORD",
    "OMEGA_MCP_INFRA_PASSWORD",
    "OMEGA_REFINEMENT_GOLD_PASSWORD",
    "OMEGA_AIRFLOW_DAG_PASSWORD",
    "OMEGA_AIRFLOW_META_PASSWORD",
    "OMEGA_SUPERSET_META_PASSWORD",
    "OMEGA_CARTRIDGE_SAP_HCM_PASSWORD",
    "OMEGA_CARTRIDGE_SAP_S4_PASSWORD",
    "OMEGA_CARTRIDGE_SAP_SF_PASSWORD",
    "OMEGA_CARTRIDGE_REPLICON_PASSWORD",
    "OMEGA_CARTRIDGE_SALESFORCE_PASSWORD",
    "OMEGA_CARTRIDGE_HUBSPOT_PASSWORD",
    "AIRFLOW_SECRET_KEY",
    "AIRFLOW_ADMIN_PASSWORD",
    "AGENT_RUNNER_TOKEN",
    "SUPERSET_SECRET_KEY",
    "SUPERSET_ADMIN_PASSWORD",
    "SUPERSET_SERVICE_PASSWORD",
    "GITHUB_DEPLOY_KEY",
  ])
}

resource "aws_secretsmanager_secret" "app" {
  for_each = local.modecissions_app_secret_names

  name        = "modecissions/${lower(each.key)}"
  description = "MODecissions runtime secret for ${each.key}"
}

output "modecissions_secret_arns" {
  description = "ARNs injected into the EC2 app host by aws-entrypoint.sh"
  value       = { for key, secret in aws_secretsmanager_secret.app : key => secret.arn }
  sensitive   = true
}
