"""Shared adversarial copy that must never cross a public Control Room boundary."""

from __future__ import annotations

from control_room_public_technical_canaries_extended import (
    EXTENDED_TECHNICAL_PUBLIC_CANARIES,
)


TECHNICAL_PUBLIC_CANARIES = (
    r"C:\srv\private\catalog.sql",
    r"\\server\share\catalog.sql",
    "/srv/private/catalog.sql",
    "//server/share/catalog",
    r"C:private\catalog",
    "$HOME/private/catalog",
    "~root/private/catalog",
    r"$env:USERPROFILE\private\catalog",
    "$env:HOME/private/catalog",
    "file://server/share/catalog",
    "FILE://server/share/catalog",
    "smb://server/share/catalog",
    "s3://private-bucket/payroll/data",
    "gs://private-bucket/payroll/data",
    "postgres://db.internal/payroll",
    "postgresql://db.internal/payroll",
    "redis://cache.internal/0",
    "jdbc:postgresql://db.internal:5432/payroll",
    "snowflake://account/private_schema",
    "arn:aws:s3:::private-payroll-bucket",
    "urn:private:payroll:dataset",
    "Portal: https://support.example.com/help?file=/srv/private/catalog",
    r"Portal: https://support.example.com/help?file=C:\srv\private\catalog",
    "Portal: https://support.example.com/help?home=$HOME/private/catalog",
    "https://support.example.com/help,/srv/private/catalog",
    "https://support.example.com/help?file=%2Fsrv%2Fprivate%2Fcatalog",
    r"https://support.example.com/help?file=\u002fsrv\u002fprivate\u002fcatalog",
    "https://support.example.com/help?file=C%3A%5Csrv%5Cprivate%5Ccatalog",
    "https://support.example.com/help?file=%252Fsrv%252Fprivate%252Fcatalog",
    "%252Fsrv%252Fprivate%252Fcatalog",
    "file%253A%252F%252Fserver%252Fshare%252Fcatalog",
    r"\x252Fsrv\x252Fprivate\x252Fcatalog",
    r"\u00252Fsrv\u00252Fprivate\u00252Fcatalog",
    "%2525252Fsrv%2525252Fprivate%2525252Fcatalog",
    "%EF%BC%8Fsrv%EF%BC%8Fprivate%EF%BC%8Fcatalog",
    "https://support.example.com/help?file=%EF%BC%8Fsrv%EF%BC%8Fprivate",
    "%EF%BC%A3%EF%BC%9A%EF%BC%BCsrv%EF%BC%BCprivate",
    "https://support.example.com/help?file=／srv／private／catalog",
    "https://support.example.com/help?file=/mnt/private/catalog",
    "https://support.example.com/help?file=/data/private/catalog",
    "https://support.example.com/help?file=catalog.sql",
    "https://support.example.com/help?download=private.parquet",
    "https://support.example.com/help#catalog.sql",
    "https://support.example.com/help?file=//server/share/catalog",
    "https://support.example.com/#//server/share/catalog",
    "https://support.example.com/help?file=private/catalog",
    r"https://support.example.com/help?path=private\catalog",
    "https://support.example.com/help?next=/public/../../mnt/private/catalog",
    "https://support.example.com/help?next=/public/home?file=/mnt/private/catalog",
    "https://[invalid",
    "https://[::1",
    "SELECT salary FROM gold_private",
    "SELECT 1",
    "VALUES (1)",
    "SELECT now()",
    "SELECT current_user",
    "SELECT pg_backend_pid()",
    "SELECT 1::integer",
    "SELECT 'x'::text",
    "SELECT 1 + 1",
    "SELECT current_catalog",
    "CREATE POLICY tenant_policy ON payroll USING (true)",
    "CREATE ROLE private_role",
    "CREATE EXTENSION pgcrypto",
    "GRANT private_role TO analyst",
    "SHOW server_version",
    "SeLeCt salary FrOm payroll",
    "Select salary From payroll",
    "SeLeCt Salary FrOm Payroll",
    'Select "salary" From "payroll"',
    "SeLeCt salary,total FrOm payroll",
    "CREATE USER private_user",
    "ALTER SYSTEM SET work_mem = '1GB'",
    "PRAGMA enable_object_cache",
    "ATTACH 'warehouse.duckdb' AS private",
    "SECURITY LABEL ON TABLE private_payroll IS 'secret'",
    "SET ROLE private_role",
    "RESET ALL",
    "SHOW ALL",
    "SHOW TIME ZONE",
    "TABLE private_payroll",
    "SELECT%201%20FROM%20payroll",
    "CREATE%20TABLE%20payroll(id%20int)",
    "CREATE+TABLE+payroll(id+int)",
    "DROP+VIEW+private_payroll",
    "GRANT+SELECT+ON+payroll+TO+private_role",
    "ALTER+SYSTEM+SET+work_mem=1",
    "https://support.example.com/help?q=CREATE+TABLE+payroll(id+int)",
    "CREATE--hidden\nTABLE payroll(id int)",
    "DROP--hidden\nVIEW private_payroll",
    "GRANT SELECT--hidden\nON payroll TO private_role",
    "CREATE/*hidden*/TABLE payroll(id int)",
    "Create Table Payroll(id int)",
    "Grant Select On Payroll To Analyst",
    "Create Materialized View Payroll",
    r"SELECT\u00201\u0020FROM\u0020payroll",
    r"CREATE\u0020TABLE\u0020payroll(id int)",
    "dataset%3Dprivate",
    "workspace%5Fid%3Dprivate",
    "catalog.sql",
    "dataset=gold_private",
    "bindings=bind-1",
    "receipt=rcpt-1",
    "provenance=prov-1",
    "tenant_id=tenant-private",
    "workspace_id=workspace-private",
    "tenant_uuid=private-alpha",
    "workspace_uuid=private-beta",
    "tenantUuid=privateAlpha",
    "activeTenantId",
    "activeWorkspaceId",
    "active_tenant_id",
    "active_workspace_id",
    "gold_private",
    "silver_people",
    "bronze_users",
    "raw_events",
    "gold.private",
    "GOLD.PRIVATE",
    "Gold.Private",
    "gOlD.pRiVaTe",
    "gold-private",
    "SILVER-PEOPLE",
    "dataset gold.private",
    "source GOLD-PRIVATE",
    "Falló gold.private.",
    "silver.people",
    "bronze.users",
    "raw.events",
    "staging.employee360",
    "materialized.payroll",
    "gold/private",
    "silver/people",
    "raw/events",
    "dataset.private",
    "dataset/private",
    "datasets.private",
    "datasets/private",
    "source.dataset.private",
    "tenant/id",
    "workspace/id",
    "tenant/uuid",
    "workspace/key",
    "tenant:id",
    "workspace:id",
    "tenant:uuid",
    "workspace:key",
    "dataset_private",
    "bindings_map",
    "receipt_id",
    "provenance_record",
    "rawSql",
    "sqlQuery",
    "querySql",
    "sqlText",
    "datasetprivate",
    "executionReceiptId",
    "sourceDatasetPrivate",
    "actionBindingsMap",
    "mathProvenanceRecord",
    r"path:C:\srv\private\catalog",
    "path:/srv/private/catalog",
    "ruta:/srv/private/catalog",
    "TRUNCATE TABLE private_payroll",
    "DROP VIEW private_payroll",
    "CREATE INDEX ix_private ON payroll(id)",
    "GRANT SELECT ON payroll TO private_role",
    "CALL private_payroll()",
    "COPY payroll TO STDOUT",
    "VACUUM ANALYZE payroll",
    "DROP MATERIALIZED VIEW private_payroll",
    "CREATE MATERIALIZED VIEW private_payroll AS SELECT 1",
    "REFRESH MATERIALIZED VIEW private_payroll",
    "GRANT SELECT, UPDATE ON payroll TO private_role",
    "WITH private AS (VALUES (1)) SELECT 1",
    "ANALYZE private_payroll",
    "COMMENT ON TABLE private_payroll IS 'private'",
    "REINDEX TABLE private_payroll",
    "SET search_path TO private",
    "SHOW search_path",
    "CREATE TYPE private_enum AS ENUM ('x')",
    "ALTER TYPE private_enum ADD VALUE 'y'",
    "DROP SEQUENCE private_seq",
    "datasetPrivate",
    "receiptId",
    "provenanceRecord",
    "gold_sap_successfactors_employee_360",
    "sap_successfactors_headcount_by_company",
    "sap_successfactors_employee_360",
    "successfactors_headcount_by_department",
    "sap-successfactors-headcount-by-company",
    "sapSuccessFactorsHeadcountByCompany",
    "goldSapSuccessFactorsEmployee360",
    "successFactorsHeadcountByDepartment",
    "sapSuccessfactorsHeadcountByCompany",
    "SAPSUCCESSFACTORSHEADCOUNTBYCOMPANY",
    "sapsuccessfactorsheadcountbycompany",
    "goldSAPSuccessFactorsEmployee360",
    "successFactorsHeadcountByCOMPANY",
    "prodSapSuccessFactorsHeadcountByCompany",
    "privateSapSuccessFactorsEmployee360",
    "sourceSuccessFactorsHeadcountByDepartment",
    "v2SapSuccessFactorsEmployee360",
    "sapSuccessFactorsTalentEmployeeProfile",
    "sapSuccessFactorsEmployeesAnomalies",
    "sapSuccessFactorsEmployeeProfile",
    "sapSuccessFactorsEmployeeTimeLatest",
    "goldSapSuccessFactorsTalentHeadcountByCohortMonth",
    "prodSapSuccessFactorsTalentEmployeeProfileV2",
    "sapSuccessFactorsHeadcountByCompanyV2",
    "prodSapSuccessFactorsEmployee360Snapshot",
    "sap_successfactors_headcount",
    "successfactors_employee360",
    "sap_successfactors",
    "sap-successfactors",
    "sap.successfactors",
    "sapSuccessFactors",
    "SAPSUCCESSFACTORS",
    "sapsuccessfactors",
    "prodSapSuccessFactors",
    "goldSapSuccessFactors",
    "privateSapSuccessFactors",
    "v2SapSuccessFactors",
    "prod_sap_successfactors",
    "Dataset materializado de SuccessFactors",
    "Ｃ：＼ｓｒｖ＼ｐｒｉｖａｔｅ＼ｃａｔａｌｏｇ．ｓｑｌ",
    "＼＼ｓｅｒｖｅｒ＼ｓｈａｒｅ＼ｃａｔａｌｏｇ．ｓｑｌ",
    "／ｓｒｖ／ｐｒｉｖａｔｅ／ｃａｔａｌｏｇ．ｓｑｌ",
    "ｇｏｌｄ＿ｓａｐ＿ｓｕｃｃｅｓｓｆａｃｔｏｒｓ＿ｅｍｐｌｏｙｅｅ＿３６０",
    "ｓａｐＳｕｃｃｅｓｓＦａｃｔｏｒｓＨｅａｄｃｏｕｎｔＢｙＣｏｍｐａｎｙ",
    "Ｄａｔａｓｅｔ materializado de SuccessFactors",
    "AKIAIOSFODNN7EXAMPLE",
    "ghp_" + "a" * 36,
    "AIza" + "A" * 35,
    "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.abcdefghijklmnop",
    "sk-proj-" + "A" * 40,
    "sk_live_" + "A" * 32,
    "glpat-" + "A" * 20,
    *EXTENDED_TECHNICAL_PUBLIC_CANARIES,
)


__all__ = ("TECHNICAL_PUBLIC_CANARIES",)
