from __future__ import annotations


EXTENDED_TECHNICAL_PUBLIC_CANARIES = (
    "-- SELECT salary FROM payroll",
    "Drop view payroll",
    "Grant select on payroll to analyst",
    "SELECT (1)",
    "SELECT ARRAY[1, 2]",
    "CREATE TEMP TABLE payroll(id int)",
    "CREATE UNIQUE INDEX idx ON payroll(id)",
    "CREATE DOMAIN private_code AS text",
    "BEGIN TRANSACTION",
    "COMMIT TRANSACTION",
    "ROLLBACK TO SAVEPOINT private_step",
    "SAVEPOINT private_step",
    "RELEASE SAVEPOINT private_step",
    "EXECUTE private_stmt",
    "FETCH NEXT FROM private_cursor",
    "DISCARD ALL",
    "COMMIT;",
    "ROLLBACK;",
    "BEGIN;",
    "END",
    "ABORT",
    "TABLE payroll;",
    "CHECKPOINT",
    "CLUSTER payroll",
    "RESET timezone",
    "SHOW timezone",
    "SET statement_timeout = 0",
    "DISCARD PLANS",
    "LISTEN private_channel",
    "UNLISTEN *",
    "LOAD 'private_library'",
    "SELECT localtimestamp;",
    "SELECT TRUE AND FALSE;",
    "SELECT TRUE AND FALSE",
    "SELECT CASE WHEN TRUE THEN 1 ELSE 0 END;",
    "SELECT CASE WHEN TRUE THEN 1 ELSE 0 END",
    "SELECT 'x'||'y'",
    "SELECT DATE '2026-07-27'",
    "SELECT INTERVAL '1 day'",
    "SELECT 1 BETWEEN 0 AND 2",
    "SELECT NULL IS NULL",
    "SELECT department",
    "FROM payroll;",
    "CREATE MACRO add_one(x) AS x + 1;",
    "CREATE OR REPLACE MACRO add_one(x) AS x + 1",
    "CREATE TEMP VIEW private_view AS TABLE payroll",
    "LOAD httpfs",
    "ANALYZE",
    "VACUUM",
    "RESET ROLE",
    "DROP INDEX payroll_idx;",
    "ATTACH DATABASE 'memory' AS archive;",
    "COPY (SELECT department FROM payroll) TO STDOUT;",
    "ALTER USER analyst WITH LOGIN;",
    "DROP USER analyst;",
    "SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;",
    "CREATE CONVERSION private_conv FOR 'UTF8' TO 'LATIN1' FROM utf8_to_latin1;",
    "CREATE CONVERSION private_conv FOR UTF8 TO LATIN1 FROM utf8_to_latin1;",
    "ALTER GROUP analysts ADD USER operator;",
    "ALTER LARGE OBJECT 123 OWNER TO analyst;",
    "DROP ROUTINE private_routine;",
    "DECLARE private_cursor CURSOR FOR TABLE payroll;",
    "MOVE NEXT FROM private_cursor;",
    "RESET SESSION AUTHORIZATION;",
    "SET CONSTRAINTS ALL DEFERRED;",
    "DETACH DATABASE archive;",
    "FORCE CHECKPOINT archive;",
    "EXPLAIN SELECT department;",
    "EXPLAIN FROM payroll;",
    "CREATE OR REPLACE TABLE payroll(id INTEGER);",
    "CREATE OR REPLACE TABLE payroll AS FROM source;",
    "RESET threads;",
    "INSTALL httpfs FROM core;",
    "FORCE INSTALL httpfs FROM core;",
    "VACUUM (ANALYZE);",
    "CREATE OR REPLACE SEQUENCE private_seq;",
    "EXPLAIN (FORMAT JSON) SELECT department;",
    "EXPLAIN (ANALYZE) SELECT department;",
    "CREATE OR REPLACE TEMP TABLE payroll(id INTEGER);",
    "CREATE OR REPLACE TEMPORARY TABLE payroll(id INTEGER);",
    "CREATE OR REPLACE TEMP VIEW private_view AS SELECT department;",
    "CREATE OR REPLACE TEMP MACRO add_one(x) AS x + 1;",
    "INSTALL 'httpfs' FROM core;",
    "INSTALL httpfs FROM 'core';",
    "EXPLAIN (FORMAT JSON) SELECT department",
    "CREATE OR REPLACE TEMP TABLE payroll(id INTEGER)",
    "INSTALL 'httpfs' FROM core",
    "ANALYZE (VERBOSE) payroll;",
    "COMMIT AND CHAIN;",
    "ROLLBACK AND CHAIN;",
    "BEGIN ISOLATION LEVEL SERIALIZABLE;",
    "CLUSTER;",
    "END AND CHAIN;",
    "ABORT AND CHAIN;",
    "ANALYZE (VERBOSE) payroll",
    "COMMIT AND CHAIN",
    "ROLLBACK AND CHAIN",
    "BEGIN ISOLATION LEVEL SERIALIZABLE",
    "CLUSTER",
    "END AND CHAIN",
    "ABORT AND CHAIN",
    "DROP EXTENSION pgcrypto;",
    "DROP TABLESPACE private_space;",
    "REVOKE private_role FROM analyst;",
    "Falló gold.private ayer",
    "Origen gold-private no disponible",
    "Data from bronze.users is ready",
    "Error in GOLD.PRIVATE source",
    "querySQL",
    "payloadSQL",
    "sql_query",
    "query_sql",
    "activeTenantUUID",
    "activeWorkspaceUUID",
    "tenantGUID",
    "workspace_guid",
    "company_id",
    "companyId",
    "companyID",
    "requestID",
    "traceID",
    "correlationID",
    "location_id",
    "departmentId",
    "employee_id",
    "source_id",
    "technical-company-id",
    "company_code",
    "externalCode",
    "sfHeadcountByCompany",
    "COMP-001",
    "COMP001",
    "employee_number",
    "person_id_external",
    "personIdExternal",
    "sfActiveHeadcount",
    "headcountByCompany",
    "tenantIdValue",
    "workspaceUUIDValue",
    "tenantIdentifierRaw",
    "api_key",
    "apiKey",
    "client_secret",
    "accessToken",
    "private_key",
    "sf_headcount_by_company",
    "sf_active_headcount",
    "headcount_by_company",
    "01J4Z6Z7E8F9G0H1J2K3M4N5P6",
    "550e8400-e29b-41d4-a716-446655440000",
    "Widget sf_active_headcount failed",
    "Field company_id missing",
    "Missing apiKey value",
    "Employee 01J4Z6Z7E8F9G0H1J2K3M4N5P6 unavailable",
    "Error in Gold.Private Dataset",
    '"gold"."private"',
    "gold . private",
    "gold..private",
    "gold:private",
    "warehouse.duckdb",
    "settings.toml",
    "private.ini",
    "server.conf",
    "audit.log",
    "script.py",
    "bootstrap.sh",
    "console/app/services/private",
    "tests/test_private.py",
    r"src\private\catalog",
    "C:private",
    "jdbc:postgresql:private_db",
    "path:private/catalog",
    r"file_path=private\catalog",
    "https://localhost/admin",
    "http://127.0.0.1:5432/private",
    "http://10.0.0.8/internal",
    "https://db.internal/admin",
    "https://[::1]/admin",
    "https://db/admin",
    "https://intranet/help",
    "https://db.corp/help",
    "http://127.1/help",
    "http://0x7f000001/help",
    "http://0177.0.0.1/help",
    "https://support.example.com/?next=/api/internal/admin",
    "https://support.example.com/?src=private/catalog",
    "https://support.example.com/#private/catalog",
    "https://support.example.com/#http://localhost:3000/admin",
    "https://example.com/help?download=http://127.0.0.1/private",
    "https://support.example.com/help?download=https://cdn.example.com/private/catalog.sql",
    "https://support.example.com/help?redirect=https://cdn.example.com/internal/admin",
    "https://support.example.com/help#https://cdn.example.com/private/catalog.sql",
    "https://support.example.com/help?artifact=private/catalog",
    "https://support.example.com/help?resource=app/services/private",
    "https://db.lan/help",
    "https://db.localdomain/help",
    "https://router.home.arpa/help",
    "localhost:5432",
    "db.internal",
    "10.0.0.8:5432",
    "Host 10.0.0.8 failed",
    "Error on 127.1 now",
    "[::1]:5432",
    "fd00::1",
    "app/services/private",
    "console/tests/private",
    "sql/bootstrap/private",
    "scripts/private/task",
    "migrations/versions/private",
    r"..\private\catalog",
    r".\private\catalog",
    "page.tsx",
    "worker.js",
    "component.ts",
    "config.cfg",
    "application.properties",
    "main.tf",
    "infra.hcl",
    "Dockerfile",
    "Basic dXNlcjpwYXNz",
    "https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX",
    "https://hooks.slack-gov.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX",
    "https://discord.com/api/webhooks/123456789/secret-token",
    "https://example.blob.core.windows.net/c?sv=2024&sig=secret",
    "https://example.com/?signature=secret",
    "https://example.com/?foo=bar;sig=secret",
    "https://example.com/#sig=secret",
    "https://example.com/?X-Amz-Signature=abc",
    "https://example.com/?X-Goog-Signature=abc",
    '{"latency_ms":42}',
    '["Comercio"]',
    "latency_ms: 42",
    "duration_ms=120",
    "row_count: 10",
    "http_status=500",
    "retry_after: 5",
    "schema_version: v2",
    "status_code=500",
    "rowCount",
    "latencyMs",
    "schemaVersion",
    "('Comercio', 'Norte')",
    "{'Comercio'}",
    "[Comercio]",
    "(('Comercio', 'Norte'),)",
    "{'Comercio', 'Norte'}",
    "[Comercio, Norte]",
    "<Connection object at 0x7FA123>",
    "Result(code=500, status=failed)",
)


__all__ = ("EXTENDED_TECHNICAL_PUBLIC_CANARIES",)
