"""
Regenerate infra/init/10_replicon_gold_seed.sql + cartridges/replicon/datasets/*.sql
from the live AWS state (datasets + analytic_apps).

Usage: python generate_seed_from_aws.py [aws_app_ip]
"""
import json
import os
import sys
import urllib.request
from pathlib import Path

AWS_IP = sys.argv[1] if len(sys.argv) > 1 else "10.0.2.175"
URL    = f"http://{AWS_IP}:8010/mcp/invoke"

ROOT       = Path(__file__).parent
SEED_FILE  = ROOT / "infra" / "init" / "10_replicon_gold_seed.sql"
DS_DIR     = ROOT / "cartridges" / "replicon" / "datasets"
DS_DIR.mkdir(parents=True, exist_ok=True)


def call(sql: str) -> list[dict]:
    req = urllib.request.Request(
        URL,
        data=json.dumps({"tool": "postgres_execute_query", "args": {"sql": sql}}).encode(),
        headers={"Content-Type": "application/json"},
    )
    out = json.loads(urllib.request.urlopen(req, timeout=60).read().decode())
    return out.get("result", {}).get("rows", [])


def quote_seed(s: str | None) -> str:
    return f"$seed${s or ''}$seed$"


def main():
    datasets = call("""
        SELECT name, layer, cartridge,
               sources::text       AS sources,
               sql_def,
               description,
               column_mapping::text AS column_mapping,
               schedule
        FROM datasets
        WHERE cartridge = 'replicon'
        ORDER BY layer, name
    """)
    apps = call("""
        SELECT name, title, html, description, cartridge_id,
               COALESCE(visibility, 'shared') AS visibility,
               COALESCE(datasets_used::text, '[]') AS datasets_used
        FROM analytic_apps
        WHERE cartridge_id = 'replicon'
        ORDER BY name
    """)

    # 1) per-dataset SQL files (only the sql_def, for diff readability)
    for d in datasets:
        path = DS_DIR / f"{d['name']}.sql"
        header = (
            f"-- {d['name']}  ({d['layer']})  cartridge: {d['cartridge']}\n"
            f"-- sources: {d['sources']}\n"
            f"-- description: {(d.get('description') or '').strip()}\n\n"
        )
        path.write_text(header + (d.get("sql_def") or "") + "\n", encoding="utf-8")

    # 2) seed SQL
    lines: list[str] = []
    lines.append(f"-- Auto-generated by generate_seed_from_aws.py from {AWS_IP}.")
    lines.append(f"-- Datasets: {len(datasets)} · Apps: {len(apps)}")
    lines.append("-- Idempotent (ON CONFLICT DO NOTHING). Re-runnable.\n")

    lines.append("-- analytic_apps lo crea refinement lazy en runtime; nos aseguramos aquí.")
    lines.append("CREATE TABLE IF NOT EXISTS analytic_apps (")
    lines.append("    name         TEXT PRIMARY KEY,")
    lines.append("    title        TEXT NOT NULL,")
    lines.append("    html         TEXT NOT NULL,")
    lines.append("    description  TEXT,")
    lines.append("    cartridge_id TEXT,")
    lines.append("    created_at   TIMESTAMPTZ DEFAULT NOW(),")
    lines.append("    updated_at   TIMESTAMPTZ DEFAULT NOW()")
    lines.append(");")
    lines.append("ALTER TABLE analytic_apps ADD COLUMN IF NOT EXISTS created_by_id BIGINT REFERENCES users(id) ON DELETE SET NULL;")
    lines.append("ALTER TABLE analytic_apps ADD COLUMN IF NOT EXISTS visibility    TEXT NOT NULL DEFAULT 'private';")
    lines.append("ALTER TABLE analytic_apps ADD COLUMN IF NOT EXISTS datasets_used TEXT[];\n")

    lines.append("-- ── Datasets (silver + master + gold) ─────────────────────────")
    for d in datasets:
        lines.append(
            "INSERT INTO datasets (name, layer, cartridge, sources, sql_def, description, column_mapping, schedule, updated_at)"
        )
        lines.append(
            f"VALUES ({quote_seed(d['name'])}, {quote_seed(d['layer'])}, {quote_seed(d['cartridge'])}, "
            f"{quote_seed(d['sources'])}::jsonb, {quote_seed(d['sql_def'])}, {quote_seed(d.get('description'))}, "
            f"{quote_seed(d.get('column_mapping') or '{}')}::jsonb, "
            f"{quote_seed(d.get('schedule'))}, NOW())"
        )
        lines.append("ON CONFLICT (name) DO NOTHING;\n")

    lines.append("-- ── Analytic Apps ───────────────────────────────────────────")
    for a in apps:
        lines.append(
            "INSERT INTO analytic_apps (name, title, html, description, cartridge_id, visibility, datasets_used, updated_at)"
        )
        # datasets_used::text comes back as '{a,b}' or '[]' — normalize to TEXT[]
        du = a.get("datasets_used") or "[]"
        # The DB column is TEXT[]; for INSERT we use '{a,b}' style
        if du.startswith("["):
            try:
                du_list = json.loads(du)
            except Exception:
                du_list = []
            du_array = "{" + ",".join(f'"{x}"' for x in du_list) + "}"
        else:
            du_array = du
        lines.append(
            f"VALUES ({quote_seed(a['name'])}, {quote_seed(a['title'])}, {quote_seed(a['html'])}, "
            f"{quote_seed(a.get('description'))}, {quote_seed(a['cartridge_id'])}, "
            f"{quote_seed(a['visibility'])}, {quote_seed(du_array)}::text[], NOW())"
        )
        lines.append("ON CONFLICT (name) DO NOTHING;\n")

    SEED_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {SEED_FILE} ({len(datasets)} datasets, {len(apps)} apps)")
    print(f"wrote {len(datasets)} files in {DS_DIR}")


if __name__ == "__main__":
    main()
