#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

if [[ -f "${ENV_FILE}" ]]; then
  echo "infra/.env already initialized — skipping"
  exit 0
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "ERROR: openssl is required to generate secrets" >&2
  exit 1
fi

INTERNAL_API_KEY="$(openssl rand -hex 32)"
JWT_SECRET_KEY="$(openssl rand -hex 32)"
SECURITY_CONTEXT_SIGNING_KEY="$(openssl rand -hex 32)"
CONTROL_ROOM_EVIDENCE_SIGNING_KEY_ID="${CONTROL_ROOM_EVIDENCE_SIGNING_KEY_ID:-evidence-$(date -u +%Y%m%d%H%M%S)}"
CONTROL_ROOM_EVIDENCE_SIGNING_KEY="${CONTROL_ROOM_EVIDENCE_SIGNING_KEY:-$(openssl rand -hex 32)}"
CONTROL_ROOM_EVIDENCE_SIGNING_PREVIOUS_KEYS="${CONTROL_ROOM_EVIDENCE_SIGNING_PREVIOUS_KEYS:-{}}"
SUPERSET_SECRET_KEY="$(openssl rand -hex 32)"
AIRFLOW_SECRET_KEY="$(openssl rand -hex 32)"
POSTGRES_PASSWORD="$(openssl rand -hex 16)"
MINIO_SECRET_KEY="$(openssl rand -hex 16)"
SUPERSET_ADMIN_PASSWORD="$(openssl rand -hex 16)"
SUPERSET_SERVICE_PASSWORD="$(openssl rand -hex 16)"
AIRFLOW_ADMIN_PASSWORD="$(openssl rand -hex 16)"
AGENT_RUNNER_TOKEN="$(openssl rand -hex 32)"
OMEGA_CONSOLE_PASSWORD="$(openssl rand -hex 16)"
OMEGA_REFINEMENT_PASSWORD="$(openssl rand -hex 16)"
OMEGA_REFINEMENT_GOLD_PASSWORD="$(openssl rand -hex 16)"
OMEGA_GOLD_PUBLISHER_PASSWORD="$(openssl rand -hex 16)"
OMEGA_GOLD_VERIFIER_PASSWORD="$(openssl rand -hex 16)"
OMEGA_OUTCOME_BINDER_PASSWORD="$(openssl rand -hex 16)"
OMEGA_VAULT_PASSWORD="$(openssl rand -hex 16)"
OMEGA_WORKSPACE_PASSWORD="$(openssl rand -hex 16)"
OMEGA_MCP_INFRA_PASSWORD="$(openssl rand -hex 16)"
OMEGA_CARTRIDGE_SAP_HCM_PASSWORD="$(openssl rand -hex 16)"
OMEGA_CARTRIDGE_SAP_S4_PASSWORD="$(openssl rand -hex 16)"
OMEGA_CARTRIDGE_SAP_SF_PASSWORD="$(openssl rand -hex 16)"
OMEGA_CARTRIDGE_SAP_B1_PASSWORD="$(openssl rand -hex 16)"
OMEGA_AIRFLOW_DAG_PASSWORD="$(openssl rand -hex 16)"
OMEGA_AIRFLOW_META_PASSWORD="$(openssl rand -hex 16)"
OMEGA_SUPERSET_META_PASSWORD="$(openssl rand -hex 16)"
OMEGA_CARTRIDGE_REPLICON_PASSWORD="$(openssl rand -hex 16)"
OMEGA_CARTRIDGE_SALESFORCE_PASSWORD="$(openssl rand -hex 16)"
INTERNAL_API_KEY_SALESFORCE_TO_CONSOLE="$(openssl rand -hex 32)"
INTERNAL_API_KEY_REPLICON_TO_CONSOLE="$(openssl rand -hex 32)"
INTERNAL_API_KEY_REPLICON_TO_MCP_INFRA="$(openssl rand -hex 32)"
INTERNAL_API_KEY_REPLICON_TO_REFINEMENT="$(openssl rand -hex 32)"

OMEGA_CARTRIDGE_HUBSPOT_PASSWORD="$(openssl rand -hex 16)"
INTERNAL_API_KEY_HUBSPOT_TO_CONSOLE="$(openssl rand -hex 32)"
INTERNAL_API_KEY_HUBSPOT_TO_MCP_INFRA="$(openssl rand -hex 32)"
INTERNAL_API_KEY_HUBSPOT_TO_REFINEMENT="$(openssl rand -hex 32)"

OMEGA_CARTRIDGE_BANXICO_PASSWORD="$(openssl rand -hex 16)"
INTERNAL_API_KEY_BANXICO_TO_CONSOLE="$(openssl rand -hex 32)"

OMEGA_CARTRIDGE_INEGI_PASSWORD="$(openssl rand -hex 16)"
INTERNAL_API_KEY_INEGI_TO_CONSOLE="$(openssl rand -hex 32)"

OMEGA_CARTRIDGE_SEC_EDGAR_PASSWORD="$(openssl rand -hex 16)"
INTERNAL_API_KEY_SEC_EDGAR_TO_CONSOLE="$(openssl rand -hex 32)"

if ! command -v python3 >/dev/null 2>&1; then
  echo "ERROR: python3 is required to generate Fernet keys" >&2
  exit 1
fi
BOOTSTRAP_PYTHON="$(command -v python3)"
FERNET_KEY_SCRIPT='import base64, os; print(base64.urlsafe_b64encode(os.urandom(32)).decode())'
VAULT_ENCRYPTION_KEY="$("${BOOTSTRAP_PYTHON}" -c "${FERNET_KEY_SCRIPT}")"

FIELD_ENCRYPTION_KEY="$("${BOOTSTRAP_PYTHON}" -c "${FERNET_KEY_SCRIPT}")"
AIRFLOW_FERNET_KEY="$("${BOOTSTRAP_PYTHON}" -c "${FERNET_KEY_SCRIPT}")"

umask 077
cat > "${ENV_FILE}" <<EOF
# Generated by infra/bootstrap.sh — do not commit.
# Re-run \`bash infra/bootstrap.sh\` only after deleting this file.

# === Required secrets (auto-generated) ===
INTERNAL_API_KEY=${INTERNAL_API_KEY}
JWT_SECRET_KEY=${JWT_SECRET_KEY}
SECURITY_CONTEXT_SIGNING_KEY=${SECURITY_CONTEXT_SIGNING_KEY}
CONTROL_ROOM_EVIDENCE_SIGNING_KEY_ID=${CONTROL_ROOM_EVIDENCE_SIGNING_KEY_ID}
CONTROL_ROOM_EVIDENCE_SIGNING_KEY=${CONTROL_ROOM_EVIDENCE_SIGNING_KEY}
CONTROL_ROOM_EVIDENCE_SIGNING_PREVIOUS_KEYS=${CONTROL_ROOM_EVIDENCE_SIGNING_PREVIOUS_KEYS}
SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
# Optional: set to the previous Superset SECRET_KEY before rotating
# SUPERSET_SECRET_KEY against an existing Superset metastore, then run
# superset-init so superset re-encrypt-secrets can migrate encrypted rows.
SUPERSET_PREVIOUS_SECRET_KEY=
AIRFLOW_SECRET_KEY=${AIRFLOW_SECRET_KEY}
AIRFLOW_FERNET_KEY=${AIRFLOW_FERNET_KEY}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
SUPERSET_ADMIN_PASSWORD=${SUPERSET_ADMIN_PASSWORD}
SUPERSET_SERVICE_PASSWORD=${SUPERSET_SERVICE_PASSWORD}
AIRFLOW_ADMIN_PASSWORD=${AIRFLOW_ADMIN_PASSWORD}
AGENT_RUNNER_TOKEN=${AGENT_RUNNER_TOKEN}

# === Service-specific Postgres roles (v1.19) ===
# Each service connects with its own login role / password instead of
# the shared \`postgres\` superuser, so a compromise of one service can't
# read/write the others' tables. See infra/init/25_service_roles.sql.
OMEGA_CONSOLE_PASSWORD=${OMEGA_CONSOLE_PASSWORD}
OMEGA_REFINEMENT_PASSWORD=${OMEGA_REFINEMENT_PASSWORD}
OMEGA_REFINEMENT_GOLD_PASSWORD=${OMEGA_REFINEMENT_GOLD_PASSWORD}
OMEGA_GOLD_PUBLISHER_PASSWORD=${OMEGA_GOLD_PUBLISHER_PASSWORD}
OMEGA_GOLD_VERIFIER_PASSWORD=${OMEGA_GOLD_VERIFIER_PASSWORD}
OMEGA_OUTCOME_BINDER_PASSWORD=${OMEGA_OUTCOME_BINDER_PASSWORD}
GOLD_VERIFIER_DATABASE_URL_HOST_FILE=${SCRIPT_DIR}/.secrets/gold_verifier_database_url
OMEGA_VAULT_PASSWORD=${OMEGA_VAULT_PASSWORD}
OMEGA_WORKSPACE_PASSWORD=${OMEGA_WORKSPACE_PASSWORD}
OMEGA_MCP_INFRA_PASSWORD=${OMEGA_MCP_INFRA_PASSWORD}

# === SAP cartridge + Airflow/Superset roles (v1.38) ===
OMEGA_CARTRIDGE_SAP_HCM_PASSWORD=${OMEGA_CARTRIDGE_SAP_HCM_PASSWORD}
OMEGA_CARTRIDGE_SAP_S4_PASSWORD=${OMEGA_CARTRIDGE_SAP_S4_PASSWORD}
OMEGA_CARTRIDGE_SAP_SF_PASSWORD=${OMEGA_CARTRIDGE_SAP_SF_PASSWORD}
OMEGA_CARTRIDGE_SAP_B1_PASSWORD=${OMEGA_CARTRIDGE_SAP_B1_PASSWORD}
OMEGA_AIRFLOW_DAG_PASSWORD=${OMEGA_AIRFLOW_DAG_PASSWORD}
OMEGA_AIRFLOW_META_PASSWORD=${OMEGA_AIRFLOW_META_PASSWORD}
OMEGA_SUPERSET_META_PASSWORD=${OMEGA_SUPERSET_META_PASSWORD}

# === Replicon cartridge (v1.40) ===
OMEGA_CARTRIDGE_REPLICON_PASSWORD=${OMEGA_CARTRIDGE_REPLICON_PASSWORD}
OMEGA_CARTRIDGE_SALESFORCE_PASSWORD=${OMEGA_CARTRIDGE_SALESFORCE_PASSWORD}
INTERNAL_API_KEY_SALESFORCE_TO_CONSOLE=${INTERNAL_API_KEY_SALESFORCE_TO_CONSOLE}
INTERNAL_API_KEY_REPLICON_TO_CONSOLE=${INTERNAL_API_KEY_REPLICON_TO_CONSOLE}
INTERNAL_API_KEY_REPLICON_TO_MCP_INFRA=${INTERNAL_API_KEY_REPLICON_TO_MCP_INFRA}
INTERNAL_API_KEY_REPLICON_TO_REFINEMENT=${INTERNAL_API_KEY_REPLICON_TO_REFINEMENT}

# === HubSpot cartridge ===
OMEGA_CARTRIDGE_HUBSPOT_PASSWORD=${OMEGA_CARTRIDGE_HUBSPOT_PASSWORD}
INTERNAL_API_KEY_HUBSPOT_TO_CONSOLE=${INTERNAL_API_KEY_HUBSPOT_TO_CONSOLE}
INTERNAL_API_KEY_HUBSPOT_TO_MCP_INFRA=${INTERNAL_API_KEY_HUBSPOT_TO_MCP_INFRA}
INTERNAL_API_KEY_HUBSPOT_TO_REFINEMENT=${INTERNAL_API_KEY_HUBSPOT_TO_REFINEMENT}

# === Banxico cartridge ===
OMEGA_CARTRIDGE_BANXICO_PASSWORD=${OMEGA_CARTRIDGE_BANXICO_PASSWORD}
INTERNAL_API_KEY_BANXICO_TO_CONSOLE=${INTERNAL_API_KEY_BANXICO_TO_CONSOLE}

# === INEGI cartridge ===
OMEGA_CARTRIDGE_INEGI_PASSWORD=${OMEGA_CARTRIDGE_INEGI_PASSWORD}
INTERNAL_API_KEY_INEGI_TO_CONSOLE=${INTERNAL_API_KEY_INEGI_TO_CONSOLE}

# === SEC EDGAR cartridge ===
OMEGA_CARTRIDGE_SEC_EDGAR_PASSWORD=${OMEGA_CARTRIDGE_SEC_EDGAR_PASSWORD}
INTERNAL_API_KEY_SEC_EDGAR_TO_CONSOLE=${INTERNAL_API_KEY_SEC_EDGAR_TO_CONSOLE}
SEC_EDGAR_USER_AGENT="OMEGA admin@modecissions.local"

# === Vault encryption at rest (v1.15) ===
# Fernet master key. Rotating this key WITHOUT re-encrypting existing rows
# makes every stored secret unrecoverable. Use \`make rotate-keys\` for a
# full regeneration of all secrets (which is itself a re-keying event).
VAULT_ENCRYPTION_KEY=${VAULT_ENCRYPTION_KEY}

# === SAP PII field encryption (v1.33) ===
# Fernet master key used by SAP cartridges to encrypt PII columns
# (Pernr, Gbdat, salaries, banking) before parquet write. Cartridges
# fail-fast at import if missing — no hardcoded fallback.
FIELD_ENCRYPTION_KEY=${FIELD_ENCRYPTION_KEY}

# === Admin usernames ===
SUPERSET_ADMIN_USER=admin
SUPERSET_SERVICE_USER=omega_service
SUPERSET_TALISMAN_ENABLED=true
SUPERSET_CSRF_ENABLED=true
SUPERSET_RATELIMIT_ENABLED=true
SUPERSET_RATELIMIT_STORAGE_URI=redis://redis:6379/1
SUPERSET_ENABLE_PROXY_FIX=true
SUPERSET_SESSION_COOKIE_SECURE=false
SUPERSET_SESSION_COOKIE_SAMESITE=Lax
SUPERSET_FORCE_HTTPS=false
AIRFLOW_ADMIN_USER=admin

# === JWT runtime ===
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=15

# === SMTP ===
SMTP_HOST=mailhog
SMTP_PORT=1025
SMTP_FROM=noreply@modecissions.local
SMTP_FROM_DOMAIN=modecissions.local
SMTP_USER=
SMTP_PASSWORD=
SMTP_USE_TLS=false
ADMIN_EMAIL=

# === VPN config delivery (WireGuard / wg-easy) ===
VPN_API_URL=
VPN_API_PASSWORD=
VPN_TOKEN_TTL_HOURS=72
VPN_CLIENT_ALLOWED_IPS=10.0.0.0/16,10.8.0.0/24
VPN_CLIENT_STRIP_DNS=true

# === CORS / public URLs ===
ALLOWED_ORIGINS=http://localhost:8000,http://localhost:8001
CONSOLE_URL=http://localhost:8000
WORKSPACE_PUBLIC_URL=http://localhost:8001
AIRFLOW_PUBLIC_URL=http://localhost:8082
SUPERSET_PUBLIC_URL=http://localhost:8088

# === Internal service URLs / DSNs ===
DATABASE_URL=postgresql+psycopg2://omega_console:${OMEGA_CONSOLE_PASSWORD}@postgres:5432/modecissions
OUTCOME_BINDER_DATABASE_URL=postgresql+psycopg2://omega_outcome_binder:${OMEGA_OUTCOME_BINDER_PASSWORD}@postgres:5432/modecissions
GOLD_DATABASE_URL=postgresql+psycopg2://omega_refinement_gold:${OMEGA_REFINEMENT_GOLD_PASSWORD}@postgres_gold:5433/modecissions_gold
GOLD_PUBLISHER_DATABASE_URL=postgresql+psycopg2://omega_gold_publisher:${OMEGA_GOLD_PUBLISHER_PASSWORD}@postgres_gold:5433/modecissions_gold
REFINEMENT_URL=http://refinement:8500
MCP_INFRA_URL=http://mcp-infra:8010
AIRFLOW_URL=http://airflow:8080
VAULT_URL=http://vault:8300
REPLICON_URL=http://replicon:8201
HUBSPOT_URL=http://hubspot:8210
SALESFORCE_URL=http://salesforce:8205
SAP_HCM_URL=http://sap-hcm:8202
SAP_S4HANA_URL=http://sap-s4hana:8204
SAP_SUCCESSFACTORS_URL=http://sap-successfactors:8203
SAP_B1_URL=http://sap-b1:8206

# === Token TTLs ===
INVITE_TOKEN_TTL_HOURS=72
RESET_TOKEN_TTL_HOURS=1

# === LLM defaults (chat/sql model picker) ===
CHAT_LLM_PROVIDER=anthropic
CHAT_LLM_MODEL=claude-haiku-4-5-20251001
SQL_LLM_MODEL=claude-sonnet-4-6

# === Replicon ===
REPLICON_API_TOKEN=
REPLICON_BASE_URL=https://na5.replicon.com/analytics

# === HubSpot ===
HUBSPOT_BASE_URL=https://api.hubapi.com
HUBSPOT_API_TOKEN=

# === Redis / embeddings (compose defaults override if blank) ===
REDIS_URL=
EMBED_DIM=
EMBED_MODEL=

# === AWS (unused unless configured) ===
AWS_REGION=us-east-1

# === LLM keys — fill via UI Settings (Fase 2) ===
ANTHROPIC_API_KEY=
GOOGLE_API_KEY=
OPENAI_API_KEY=

# === Integrations — fill via UI Settings (Fase 2) ===
REPLICON_TOKEN=
SF_CLIENT_ID=
SF_CLIENT_SECRET=
SF_BASE_URL=
SF_COMPANY_ID=
SF_TOKEN_URL=
SAP_HCM_USER=
SAP_HCM_PASS=
SAP_HCM_BASE_URL=
SAP_HCM_CLIENT_MANDANT=
SAP_S4_USER=
SAP_S4_PASS=
SAP_S4_BASE_URL=
SAP_S4_CLIENT_MANDANT=100
SAP_S4_API_KEY=
OUTLOOK_APP_PASSWORD=
OUTLOOK_RECEIVER_EMAIL=devnull@modecissions.local
OUTLOOK_SENDER_EMAIL=devnull@modecissions.local

# === S3 / DB extras (optional) ===
S3_BUCKET_NAME=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_SESSION_TOKEN=
AWS_DEFAULT_REGION=us-east-1
PG_DSN=
PG_HOST=postgres
PG_PORT=5432
PG_DB=modecissions
PG_USER=omega_mcp_infra
PG_PASSWORD=${OMEGA_MCP_INFRA_PASSWORD}
PG_GOLD_HOST=postgres_gold
PG_GOLD_PORT=5433
PG_GOLD_DB=modecissions_gold
PG_GOLD_USER=omega_refinement_gold
PG_GOLD_PASSWORD=${OMEGA_REFINEMENT_GOLD_PASSWORD}
MINIO_ENDPOINT=minio:9000
MINIO_ACCESS_KEY=minio
MINIO_BUCKET=lakehouse
MINIO_SECURE=false
MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}

# === App env ===
# Local compose defaults to production guardrails. Override explicitly only
# for isolated development runs.
APP_ENV=production
ALLOW_RCE_TOOLS=false
RATE_LIMIT_ENABLED=true
TRUSTED_PROXY_IPS=
COOKIE_SECURE=
CONTROL_ROOM_ENABLE_EXTERNAL_WRITEBACK=false
CONTROL_ROOM_ENABLE_EXTERNAL_DELIVERY=false

# === Bootstrap admin (manual first boot only) ===
# Uncomment for:
#   docker compose exec -e BOOTSTRAP_ADMIN_PASSWORD console python -m app.bootstrap_admin <email>
# BOOTSTRAP_ADMIN_EMAIL=admin@your-domain.test
# BOOTSTRAP_ADMIN_PASSWORD=
# BOOTSTRAP_ADMIN_FULL_NAME=System Administrator
EOF

install -d -m 0700 "${SCRIPT_DIR}/.secrets"
printf 'postgresql://omega_gold_verifier:%s@postgres_gold:5433/modecissions_gold\n' \
  "${OMEGA_GOLD_VERIFIER_PASSWORD}" \
  >"${SCRIPT_DIR}/.secrets/gold_verifier_database_url"
chmod 0600 "${SCRIPT_DIR}/.secrets/gold_verifier_database_url"

echo "infra/.env generated. Next: make up"
