#!/usr/bin/env bash
# infra/bootstrap.sh — one-shot generator for infra/.env
# Idempotent: re-running with an existing infra/.env is a no-op.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

if [[ -f "${ENV_FILE}" ]]; then
  echo "infra/.env already initialized — skipping"
  exit 0
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "ERROR: openssl is required to generate secrets" >&2
  exit 1
fi

INTERNAL_API_KEY="$(openssl rand -hex 32)"
JWT_SECRET_KEY="$(openssl rand -hex 32)"
SUPERSET_SECRET_KEY="$(openssl rand -hex 32)"
AIRFLOW_SECRET_KEY="$(openssl rand -hex 32)"
POSTGRES_PASSWORD="$(openssl rand -hex 16)"
MINIO_SECRET_KEY="$(openssl rand -hex 16)"
SUPERSET_ADMIN_PASSWORD="$(openssl rand -hex 16)"
AIRFLOW_ADMIN_PASSWORD="$(openssl rand -hex 16)"

# Sprint v1.19: per-service Postgres roles (least-privilege). Each
# service gets its own login role and its own password so a compromise
# of one service can't reach the other tables — most importantly,
# vault_entries is locked to the omega_vault role. See
# infra/init/25_service_roles.sql for the GRANTs.
OMEGA_CONSOLE_PASSWORD="$(openssl rand -hex 16)"
OMEGA_REFINEMENT_PASSWORD="$(openssl rand -hex 16)"
OMEGA_REFINEMENT_GOLD_PASSWORD="$(openssl rand -hex 16)"
OMEGA_VAULT_PASSWORD="$(openssl rand -hex 16)"
OMEGA_WORKSPACE_PASSWORD="$(openssl rand -hex 16)"
OMEGA_MCP_INFRA_PASSWORD="$(openssl rand -hex 16)"

# Sprint v1.15: Fernet master key for vault encryption at rest.
# Generated via the `cryptography` package because Fernet keys are
# URL-safe base64 of 32 random bytes — `openssl rand -base64 32` is
# almost-but-not-quite the right format.
if ! command -v python3 >/dev/null 2>&1; then
  echo "ERROR: python3 is required to generate VAULT_ENCRYPTION_KEY" >&2
  exit 1
fi
VAULT_ENCRYPTION_KEY="$(python3 -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())')"

umask 077
cat > "${ENV_FILE}" <<EOF
# Generated by infra/bootstrap.sh — do not commit.
# Re-run \`bash infra/bootstrap.sh\` only after deleting this file.

# === Required secrets (auto-generated) ===
INTERNAL_API_KEY=${INTERNAL_API_KEY}
JWT_SECRET_KEY=${JWT_SECRET_KEY}
SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
AIRFLOW_SECRET_KEY=${AIRFLOW_SECRET_KEY}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
SUPERSET_ADMIN_PASSWORD=${SUPERSET_ADMIN_PASSWORD}
AIRFLOW_ADMIN_PASSWORD=${AIRFLOW_ADMIN_PASSWORD}

# === Service-specific Postgres roles (v1.19) ===
# Each service connects with its own login role / password instead of
# the shared \`postgres\` superuser, so a compromise of one service can't
# read/write the others' tables. See infra/init/25_service_roles.sql.
OMEGA_CONSOLE_PASSWORD=${OMEGA_CONSOLE_PASSWORD}
OMEGA_REFINEMENT_PASSWORD=${OMEGA_REFINEMENT_PASSWORD}
OMEGA_REFINEMENT_GOLD_PASSWORD=${OMEGA_REFINEMENT_GOLD_PASSWORD}
OMEGA_VAULT_PASSWORD=${OMEGA_VAULT_PASSWORD}
OMEGA_WORKSPACE_PASSWORD=${OMEGA_WORKSPACE_PASSWORD}
OMEGA_MCP_INFRA_PASSWORD=${OMEGA_MCP_INFRA_PASSWORD}

# === Vault encryption at rest (v1.15) ===
# Fernet master key. Rotating this key WITHOUT re-encrypting existing rows
# makes every stored secret unrecoverable. Use \`make rotate-keys\` for a
# full regeneration of all secrets (which is itself a re-keying event).
VAULT_ENCRYPTION_KEY=${VAULT_ENCRYPTION_KEY}

# === Admin usernames ===
SUPERSET_ADMIN_USER=admin
AIRFLOW_ADMIN_USER=admin

# === JWT runtime ===
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=15

# === SMTP ===
SMTP_HOST=mailhog
SMTP_PORT=1025
SMTP_FROM=noreply@modecissions.local
SMTP_USER=
SMTP_PASSWORD=
SMTP_USE_TLS=false

# === CORS / public URLs ===
ALLOWED_ORIGINS=http://localhost:8000,http://localhost:8001
CONSOLE_URL=http://localhost:8000
WORKSPACE_PUBLIC_URL=http://localhost:8001

# === Token TTLs ===
INVITE_TOKEN_TTL_HOURS=72
RESET_TOKEN_TTL_HOURS=1

# === LLM defaults (chat/sql model picker) ===
CHAT_LLM_PROVIDER=gemini
CHAT_LLM_MODEL=gemini-1.5-flash
SQL_LLM_MODEL=claude-sonnet-4-6
GEMINI_CACHE_ENABLED=true

# === Replicon ===
REPLICON_BASE_URL=https://na5.replicon.com/analytics
REPLICON_USE_DEMO=false
REPLICON_MOCK_USER_COUNT=

# === Redis / embeddings (compose defaults override if blank) ===
REDIS_URL=
EMBED_DIM=
EMBED_MODEL=

# === AWS (unused unless configured) ===
AWS_REGION=us-east-1

# === LLM keys — fill via UI Settings (Fase 2) ===
GEMINI_API_KEY=
ANTHROPIC_API_KEY=
GOOGLE_API_KEY=
OPENAI_API_KEY=

# === Integrations — fill via UI Settings (Fase 2) ===
REPLICON_TOKEN=
SF_CLIENT_ID=
SF_CLIENT_SECRET=
SF_BASE_URL=
SF_COMPANY_ID=
SF_TOKEN_URL=
SAP_HCM_USER=
SAP_HCM_PASS=
SAP_HCM_BASE_URL=
SAP_HCM_CLIENT_MANDANT=
SAP_S4_USER=
SAP_S4_PASS=
OUTLOOK_APP_PASSWORD=

# === S3 / DB extras (optional) ===
S3_BUCKET_NAME=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
PG_DSN=
MINIO_ROOT_PASSWORD=
EOF

echo "infra/.env generated. Next: make up"
