#!/usr/bin/env bash
# infra/bootstrap.sh — one-shot generator for infra/.env
# Idempotent: re-running with an existing infra/.env is a no-op.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

if [[ -f "${ENV_FILE}" ]]; then
  echo "infra/.env already initialized — skipping"
  exit 0
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "ERROR: openssl is required to generate secrets" >&2
  exit 1
fi

INTERNAL_API_KEY="$(openssl rand -hex 32)"
JWT_SECRET_KEY="$(openssl rand -hex 32)"
SUPERSET_SECRET_KEY="$(openssl rand -hex 32)"
AIRFLOW_SECRET_KEY="$(openssl rand -hex 32)"
POSTGRES_PASSWORD="$(openssl rand -hex 16)"
MINIO_SECRET_KEY="$(openssl rand -hex 16)"
SUPERSET_ADMIN_PASSWORD="$(openssl rand -hex 16)"
SUPERSET_SERVICE_PASSWORD="$(openssl rand -hex 16)"
AIRFLOW_ADMIN_PASSWORD="$(openssl rand -hex 16)"
AGENT_RUNNER_TOKEN="$(openssl rand -hex 32)"

# Sprint v1.19: per-service Postgres roles (least-privilege). Each
# service gets its own login role and its own password so a compromise
# of one service can't reach the other tables — most importantly,
# vault_entries is locked to the omega_vault role. See
# infra/init/25_service_roles.sql for the GRANTs.
OMEGA_CONSOLE_PASSWORD="$(openssl rand -hex 16)"
OMEGA_REFINEMENT_PASSWORD="$(openssl rand -hex 16)"
OMEGA_REFINEMENT_GOLD_PASSWORD="$(openssl rand -hex 16)"
OMEGA_VAULT_PASSWORD="$(openssl rand -hex 16)"
OMEGA_WORKSPACE_PASSWORD="$(openssl rand -hex 16)"
OMEGA_MCP_INFRA_PASSWORD="$(openssl rand -hex 16)"

# Sprint v1.38 (audit B5+B6 P0.5): least-privilege roles for the
# SAP cartridges, the two Airflow surfaces (metastore + DAG runtime),
# and the Superset metastore. Created by
# infra/init/36_cartridge_and_meta_roles.sql.
OMEGA_CARTRIDGE_SAP_HCM_PASSWORD="$(openssl rand -hex 16)"
OMEGA_CARTRIDGE_SAP_S4_PASSWORD="$(openssl rand -hex 16)"
OMEGA_CARTRIDGE_SAP_SF_PASSWORD="$(openssl rand -hex 16)"
OMEGA_AIRFLOW_DAG_PASSWORD="$(openssl rand -hex 16)"
OMEGA_AIRFLOW_META_PASSWORD="$(openssl rand -hex 16)"
OMEGA_SUPERSET_META_PASSWORD="$(openssl rand -hex 16)"

# Sprint v1.40 (replicon cartridge restored): DB role + 3 pair keys
# (replicon -> console / mcp-infra / refinement). Created by
# infra/init/37_replicon_role_and_tables.sql.
OMEGA_CARTRIDGE_REPLICON_PASSWORD="$(openssl rand -hex 16)"
# Salesforce cartridge: DB role created by
# infra/init/93_salesforce_role_and_tables.sql.
OMEGA_CARTRIDGE_SALESFORCE_PASSWORD="$(openssl rand -hex 16)"
INTERNAL_API_KEY_REPLICON_TO_CONSOLE="$(openssl rand -hex 32)"
INTERNAL_API_KEY_REPLICON_TO_MCP_INFRA="$(openssl rand -hex 32)"
INTERNAL_API_KEY_REPLICON_TO_REFINEMENT="$(openssl rand -hex 32)"

# HubSpot cartridge (same runtime contract as Replicon).
OMEGA_CARTRIDGE_HUBSPOT_PASSWORD="$(openssl rand -hex 16)"
INTERNAL_API_KEY_HUBSPOT_TO_CONSOLE="$(openssl rand -hex 32)"
INTERNAL_API_KEY_HUBSPOT_TO_MCP_INFRA="$(openssl rand -hex 32)"
INTERNAL_API_KEY_HUBSPOT_TO_REFINEMENT="$(openssl rand -hex 32)"

# Sprint v1.15: Fernet master key for vault encryption at rest.
# Fernet keys are URL-safe base64 of 32 random bytes. Generate them
# with Python's stdlib so bootstrap does not depend on host cryptography/cffi.
if ! command -v python3 >/dev/null 2>&1; then
  echo "ERROR: python3 is required to generate VAULT_ENCRYPTION_KEY" >&2
  exit 1
fi
BOOTSTRAP_PYTHON="$(command -v python3)"
FERNET_KEY_SCRIPT='import base64, os; print(base64.urlsafe_b64encode(os.urandom(32)).decode())'
VAULT_ENCRYPTION_KEY="$("${BOOTSTRAP_PYTHON}" -c "${FERNET_KEY_SCRIPT}")"

# Sprint v1.33 (audit B1 P0): Fernet key used by SAP cartridges
# (sap_hcm / sap_s4hana / sap_successfactors) to encrypt PII columns at
# rest before they land in MinIO/parquet. The cartridges refuse to start
# without it — there is no longer a hardcoded fallback.
FIELD_ENCRYPTION_KEY="$("${BOOTSTRAP_PYTHON}" -c "${FERNET_KEY_SCRIPT}")"

umask 077
cat > "${ENV_FILE}" <<EOF
# Generated by infra/bootstrap.sh — do not commit.
# Re-run \`bash infra/bootstrap.sh\` only after deleting this file.

# === Required secrets (auto-generated) ===
INTERNAL_API_KEY=${INTERNAL_API_KEY}
JWT_SECRET_KEY=${JWT_SECRET_KEY}
SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
# Optional: set to the previous Superset SECRET_KEY before rotating
# SUPERSET_SECRET_KEY against an existing Superset metastore, then run
# superset-init so `superset re-encrypt-secrets` can migrate encrypted rows.
SUPERSET_PREVIOUS_SECRET_KEY=
AIRFLOW_SECRET_KEY=${AIRFLOW_SECRET_KEY}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
SUPERSET_ADMIN_PASSWORD=${SUPERSET_ADMIN_PASSWORD}
SUPERSET_SERVICE_PASSWORD=${SUPERSET_SERVICE_PASSWORD}
AIRFLOW_ADMIN_PASSWORD=${AIRFLOW_ADMIN_PASSWORD}
AGENT_RUNNER_TOKEN=${AGENT_RUNNER_TOKEN}

# === Service-specific Postgres roles (v1.19) ===
# Each service connects with its own login role / password instead of
# the shared \`postgres\` superuser, so a compromise of one service can't
# read/write the others' tables. See infra/init/25_service_roles.sql.
OMEGA_CONSOLE_PASSWORD=${OMEGA_CONSOLE_PASSWORD}
OMEGA_REFINEMENT_PASSWORD=${OMEGA_REFINEMENT_PASSWORD}
OMEGA_REFINEMENT_GOLD_PASSWORD=${OMEGA_REFINEMENT_GOLD_PASSWORD}
OMEGA_VAULT_PASSWORD=${OMEGA_VAULT_PASSWORD}
OMEGA_WORKSPACE_PASSWORD=${OMEGA_WORKSPACE_PASSWORD}
OMEGA_MCP_INFRA_PASSWORD=${OMEGA_MCP_INFRA_PASSWORD}

# === SAP cartridge + Airflow/Superset roles (v1.38) ===
OMEGA_CARTRIDGE_SAP_HCM_PASSWORD=${OMEGA_CARTRIDGE_SAP_HCM_PASSWORD}
OMEGA_CARTRIDGE_SAP_S4_PASSWORD=${OMEGA_CARTRIDGE_SAP_S4_PASSWORD}
OMEGA_CARTRIDGE_SAP_SF_PASSWORD=${OMEGA_CARTRIDGE_SAP_SF_PASSWORD}
OMEGA_AIRFLOW_DAG_PASSWORD=${OMEGA_AIRFLOW_DAG_PASSWORD}
OMEGA_AIRFLOW_META_PASSWORD=${OMEGA_AIRFLOW_META_PASSWORD}
OMEGA_SUPERSET_META_PASSWORD=${OMEGA_SUPERSET_META_PASSWORD}

# === Replicon cartridge (v1.40) ===
OMEGA_CARTRIDGE_REPLICON_PASSWORD=${OMEGA_CARTRIDGE_REPLICON_PASSWORD}
OMEGA_CARTRIDGE_SALESFORCE_PASSWORD=${OMEGA_CARTRIDGE_SALESFORCE_PASSWORD}
INTERNAL_API_KEY_REPLICON_TO_CONSOLE=${INTERNAL_API_KEY_REPLICON_TO_CONSOLE}
INTERNAL_API_KEY_REPLICON_TO_MCP_INFRA=${INTERNAL_API_KEY_REPLICON_TO_MCP_INFRA}
INTERNAL_API_KEY_REPLICON_TO_REFINEMENT=${INTERNAL_API_KEY_REPLICON_TO_REFINEMENT}

# === HubSpot cartridge ===
OMEGA_CARTRIDGE_HUBSPOT_PASSWORD=${OMEGA_CARTRIDGE_HUBSPOT_PASSWORD}
INTERNAL_API_KEY_HUBSPOT_TO_CONSOLE=${INTERNAL_API_KEY_HUBSPOT_TO_CONSOLE}
INTERNAL_API_KEY_HUBSPOT_TO_MCP_INFRA=${INTERNAL_API_KEY_HUBSPOT_TO_MCP_INFRA}
INTERNAL_API_KEY_HUBSPOT_TO_REFINEMENT=${INTERNAL_API_KEY_HUBSPOT_TO_REFINEMENT}

# === Vault encryption at rest (v1.15) ===
# Fernet master key. Rotating this key WITHOUT re-encrypting existing rows
# makes every stored secret unrecoverable. Use \`make rotate-keys\` for a
# full regeneration of all secrets (which is itself a re-keying event).
VAULT_ENCRYPTION_KEY=${VAULT_ENCRYPTION_KEY}

# === SAP PII field encryption (v1.33) ===
# Fernet master key used by SAP cartridges to encrypt PII columns
# (Pernr, Gbdat, salaries, banking) before parquet write. Cartridges
# fail-fast at import if missing — no hardcoded fallback.
FIELD_ENCRYPTION_KEY=${FIELD_ENCRYPTION_KEY}

# === Admin usernames ===
SUPERSET_ADMIN_USER=admin
SUPERSET_SERVICE_USER=omega_service
SUPERSET_TALISMAN_ENABLED=true
SUPERSET_CSRF_ENABLED=true
SUPERSET_RATELIMIT_ENABLED=true
SUPERSET_RATELIMIT_STORAGE_URI=redis://redis:6379/1
SUPERSET_ENABLE_PROXY_FIX=true
SUPERSET_SESSION_COOKIE_SECURE=false
SUPERSET_SESSION_COOKIE_SAMESITE=Lax
SUPERSET_FORCE_HTTPS=false
AIRFLOW_ADMIN_USER=admin

# === JWT runtime ===
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=15

# === SMTP ===
SMTP_HOST=mailhog
SMTP_PORT=1025
SMTP_FROM=noreply@modecissions.local
SMTP_FROM_DOMAIN=modecissions.local
SMTP_USER=
SMTP_PASSWORD=
SMTP_USE_TLS=false
ADMIN_EMAIL=

# === VPN config delivery (WireGuard / wg-easy) ===
VPN_API_URL=
VPN_API_PASSWORD=
VPN_TOKEN_TTL_HOURS=72
VPN_CLIENT_ALLOWED_IPS=10.0.0.0/16,10.8.0.0/24
VPN_CLIENT_STRIP_DNS=true

# === CORS / public URLs ===
ALLOWED_ORIGINS=http://localhost:8000,http://localhost:8001
CONSOLE_URL=http://localhost:8000
WORKSPACE_PUBLIC_URL=http://localhost:8001
AIRFLOW_PUBLIC_URL=http://localhost:8082
SUPERSET_PUBLIC_URL=http://localhost:8088

# === Internal service URLs / DSNs ===
DATABASE_URL=postgresql+psycopg2://omega_console:${OMEGA_CONSOLE_PASSWORD}@postgres:5432/modecissions
GOLD_DATABASE_URL=postgresql+psycopg2://omega_refinement_gold:${OMEGA_REFINEMENT_GOLD_PASSWORD}@postgres_gold:5433/modecissions_gold
REFINEMENT_URL=http://refinement:8500
MCP_INFRA_URL=http://mcp-infra:8010
AIRFLOW_URL=http://airflow:8080
VAULT_URL=http://vault:8300
REPLICON_URL=http://replicon:8201
HUBSPOT_URL=http://hubspot:8210
SAP_HCM_URL=http://sap-hcm:8202
SAP_S4HANA_URL=http://sap-s4hana:8204
SAP_SUCCESSFACTORS_URL=http://sap-successfactors:8203

# === Token TTLs ===
INVITE_TOKEN_TTL_HOURS=72
RESET_TOKEN_TTL_HOURS=1

# === LLM defaults (chat/sql model picker) ===
CHAT_LLM_PROVIDER=gemini
CHAT_LLM_MODEL=gemini-1.5-flash
SQL_LLM_MODEL=claude-sonnet-4-6
GEMINI_CACHE_ENABLED=true

# === Replicon ===
REPLICON_API_TOKEN=
REPLICON_BASE_URL=https://na5.replicon.com/analytics
REPLICON_USE_DEMO=false
REPLICON_MOCK_USER_COUNT=

# === HubSpot ===
HUBSPOT_BASE_URL=https://api.hubapi.com
HUBSPOT_API_TOKEN=

# === Redis / embeddings (compose defaults override if blank) ===
REDIS_URL=
EMBED_DIM=
EMBED_MODEL=

# === AWS (unused unless configured) ===
AWS_REGION=us-east-1

# === LLM keys — fill via UI Settings (Fase 2) ===
GEMINI_API_KEY=
ANTHROPIC_API_KEY=
GOOGLE_API_KEY=
OPENAI_API_KEY=

# === Integrations — fill via UI Settings (Fase 2) ===
REPLICON_TOKEN=
SF_CLIENT_ID=
SF_CLIENT_SECRET=
SF_BASE_URL=
SF_COMPANY_ID=
SF_TOKEN_URL=
SAP_HCM_USER=
SAP_HCM_PASS=
SAP_HCM_BASE_URL=
SAP_HCM_CLIENT_MANDANT=
SAP_S4_USER=
SAP_S4_PASS=
SAP_S4_BASE_URL=
SAP_S4_CLIENT_MANDANT=100
SAP_S4_API_KEY=
OUTLOOK_APP_PASSWORD=
OUTLOOK_RECEIVER_EMAIL=devnull@modecissions.local
OUTLOOK_SENDER_EMAIL=devnull@modecissions.local

# === S3 / DB extras (optional) ===
S3_BUCKET_NAME=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_SESSION_TOKEN=
AWS_DEFAULT_REGION=us-east-1
PG_DSN=
PG_HOST=postgres
PG_PORT=5432
PG_DB=modecissions
PG_USER=omega_mcp_infra
PG_PASSWORD=${OMEGA_MCP_INFRA_PASSWORD}
PG_GOLD_HOST=postgres_gold
PG_GOLD_PORT=5433
PG_GOLD_DB=modecissions_gold
PG_GOLD_USER=omega_refinement_gold
PG_GOLD_PASSWORD=${OMEGA_REFINEMENT_GOLD_PASSWORD}
MINIO_ENDPOINT=minio:9000
MINIO_ACCESS_KEY=minio
MINIO_BUCKET=lakehouse
MINIO_SECURE=false
MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}

# === App env ===
# Local compose defaults to production guardrails. Override explicitly only
# for isolated development runs.
APP_ENV=production
ALLOW_RCE_TOOLS=false
RATE_LIMIT_ENABLED=true
TRUSTED_PROXY_IPS=
COOKIE_SECURE=
CONTROL_ROOM_ENABLE_EXTERNAL_WRITEBACK=false
CONTROL_ROOM_ENABLE_EXTERNAL_DELIVERY=false

# === Bootstrap admin (manual first boot only) ===
# Uncomment for:
#   docker compose exec -e BOOTSTRAP_ADMIN_PASSWORD console python -m app.bootstrap_admin <email>
# BOOTSTRAP_ADMIN_EMAIL=admin@your-domain.test
# BOOTSTRAP_ADMIN_PASSWORD=
# BOOTSTRAP_ADMIN_FULL_NAME=System Administrator
EOF

echo "infra/.env generated. Next: make up"
