services:
  console:
    environment:
      RATE_LIMIT_ENABLED: "false"

  airflow:
    environment:
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "${AIRFLOW_DAGS_ARE_PAUSED_AT_CREATION:-false}"

  airflow-scheduler:
    environment:
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "${AIRFLOW_DAGS_ARE_PAUSED_AT_CREATION:-false}"
