from __future__ import annotations

import re
from pathlib import Path

import pytest
import yaml


REPO_ROOT  = Path(__file__).resolve().parents[1]
MIGRATION  = REPO_ROOT / "infra" / "init" / "25_service_roles.sql"
MARKETPLACE_MIGRATION = REPO_ROOT / "infra" / "init" / "73_marketplace_installations.sql"
IDENTITY_BOUNDARY_MIGRATION = REPO_ROOT / "infra" / "init" / "99zzy_identity_session_boundary.sql"
COMPOSE    = REPO_ROOT / "infra" / "docker-compose.yml"
BOOTSTRAP  = REPO_ROOT / "infra" / "bootstrap.sh"
ENV_EXAMPLE = REPO_ROOT / "infra" / ".env.example"


OMEGA_ROLES = (
    "omega_console",
    "omega_refinement",
    "omega_vault",
    "omega_workspace",
    "omega_mcp_infra",
)
NON_VAULT_ROLES = tuple(r for r in OMEGA_ROLES if r != "omega_vault")
PASSWORD_VARS = tuple(f"{r.upper()}_PASSWORD" for r in OMEGA_ROLES)


def test_migration_file_exists():
    assert MIGRATION.is_file(), f"{MIGRATION} missing"


@pytest.mark.parametrize("role", OMEGA_ROLES)
def test_migration_creates_each_role(role):
    sql = MIGRATION.read_text(encoding="utf-8")
    pattern = rf"CREATE ROLE {role}\b"
    assert re.search(pattern, sql), (
        f"migration is missing CREATE ROLE for {role!r}"
    )


def test_migration_defines_exactly_five_roles():
    sql = MIGRATION.read_text(encoding="utf-8")
    found = sorted(set(re.findall(r"CREATE ROLE (omega_[a-z_]+)\b", sql)))
    assert found == sorted(OMEGA_ROLES), (
        f"role set drift: found {found}, expected {sorted(OMEGA_ROLES)}"
    )


@pytest.mark.parametrize("role", NON_VAULT_ROLES)
def test_vault_entries_revoked_for_non_vault_roles(role):
    sql = MIGRATION.read_text(encoding="utf-8")
    pattern = rf"REVOKE ALL ON vault_entries FROM {role}\b"
    assert re.search(pattern, sql), (
        f"{role} must have REVOKE ALL ON vault_entries"
    )


def test_vault_role_has_full_crud_on_vault_entries():
    sql = MIGRATION.read_text(encoding="utf-8")
    pattern = r"GRANT\s+SELECT,\s*INSERT,\s*UPDATE,\s*DELETE\s+ON\s+vault_entries\s+TO\s+omega_vault"
    assert re.search(pattern, sql, flags=re.IGNORECASE), (
        "omega_vault must have SELECT/INSERT/UPDATE/DELETE on vault_entries"
    )


def test_no_other_role_has_grants_on_vault_entries():
    sql = MIGRATION.read_text(encoding="utf-8")
    grants = re.findall(
        r"GRANT\s+[^;]*?\s+ON\s+vault_entries\s+TO\s+(\w+)",
        sql, flags=re.IGNORECASE,
    )
    leaked = sorted(set(g for g in grants if g != "omega_vault"))
    assert not leaked, (
        f"vault_entries GRANT escaped to non-vault role(s): {leaked}"
    )


def test_migration_aborts_on_missing_password_setting():
    sql = MIGRATION.read_text(encoding="utf-8")
    raises = re.findall(
        r"RAISE\s+EXCEPTION\s+'app\.(omega_[a-z_]+)_password not set",
        sql,
    )
    assert sorted(set(raises)) == sorted(OMEGA_ROLES), (
        f"missing empty-password guard for some role(s): "
        f"got {sorted(set(raises))}, expected {sorted(OMEGA_ROLES)}"
    )


@pytest.mark.parametrize("var", PASSWORD_VARS)
def test_bootstrap_generates_each_omega_password_assignment(var):
    src = BOOTSTRAP.read_text(encoding="utf-8")
    assert re.search(rf"^{var}=\"\$\(openssl rand -hex 16\)\"$",
                     src, flags=re.MULTILINE), (
        f"{var} not generated by bootstrap.sh"
    )
    assert f"{var}=${{{var}}}" in src, (
        f"{var} not written into infra/.env by bootstrap.sh heredoc"
    )


def test_env_example_documents_all_five_omega_passwords():
    src = ENV_EXAMPLE.read_text(encoding="utf-8")
    for var in PASSWORD_VARS:
        assert var in src, f".env.example missing {var}"


def _compose_doc():
    return yaml.safe_load(COMPOSE.read_text(encoding="utf-8"))


def test_postgres_service_passes_pgoptions_with_five_app_settings():
    doc = _compose_doc()
    pg_env = doc["services"]["postgres"]["environment"]
    assert "PGOPTIONS" in pg_env, "postgres service missing PGOPTIONS"
    pgo = pg_env["PGOPTIONS"]
    for role in OMEGA_ROLES:
        setting = f"app.{role}_password"
        assert setting in pgo, (
            f"PGOPTIONS missing -c {setting}=…  ({pgo!r})"
        )


SERVICE_TO_ROLE = {
    "console":    "omega_console",
    "refinement": "omega_refinement",
    "vault":      "omega_vault",
    "workspace":  "omega_workspace",
}


@pytest.mark.parametrize("service,role", list(SERVICE_TO_ROLE.items()))
def test_each_service_database_url_uses_its_omega_role(service, role):
    doc = _compose_doc()
    env = doc["services"][service]["environment"]
    db_url = env["DATABASE_URL"]
    assert f"://{role}:" in db_url, (
        f"{service} DATABASE_URL doesn't use {role}: {db_url!r}"
    )
    pwd_var = f"{role.upper()}_PASSWORD"
    assert f"${{{pwd_var}" in db_url, (
        f"{service} DATABASE_URL doesn't reference {pwd_var}: {db_url!r}"
    )
    assert "postgres:${POSTGRES_PASSWORD" not in db_url, (
        f"{service} DATABASE_URL still uses superuser postgres: {db_url!r}"
    )


def test_mcp_infra_uses_omega_mcp_infra_via_pg_user():
    doc = _compose_doc()
    env = doc["services"]["mcp-infra"]["environment"]
    assert env["PG_USER"] == "omega_mcp_infra", (
        f"mcp-infra PG_USER must be omega_mcp_infra, got {env['PG_USER']!r}"
    )
    assert "OMEGA_MCP_INFRA_PASSWORD" in env["PG_PASSWORD"], (
        f"mcp-infra PG_PASSWORD must reference OMEGA_MCP_INFRA_PASSWORD; "
        f"got {env['PG_PASSWORD']!r}"
    )


def test_refinement_gold_database_url_uses_omega_gold_role():
    doc = _compose_doc()
    gold = doc["services"]["refinement"]["environment"]["GOLD_DATABASE_URL"]
    assert "://omega_refinement_gold:" in gold
    assert "OMEGA_REFINEMENT_GOLD_PASSWORD" in gold
    assert "://postgres:" not in gold


def test_no_in_scope_service_still_uses_postgres_superuser_for_main_db():
    doc = _compose_doc()
    in_scope = ("console", "refinement", "vault", "workspace")
    bad = []
    for svc in in_scope:
        url = doc["services"][svc]["environment"].get("DATABASE_URL", "")
        if "postgres:${POSTGRES_PASSWORD" in url:
            bad.append(f"{svc}: {url}")
    assert not bad, (
        f"in-scope service(s) still use the postgres superuser:\n  "
        + "\n  ".join(bad)
    )


def _role_section(sql: str, role: str) -> str:
    starts = [
        (m.start(), m.group(1))
        for m in re.finditer(
            r"GRANT\s+CONNECT\s+ON\s+DATABASE\s+\w+\s+TO\s+(omega_[a-z_]+)",
            sql,
        )
    ]
    starts.sort()
    for i, (pos, found_role) in enumerate(starts):
        if found_role == role:
            end = starts[i + 1][0] if i + 1 < len(starts) else len(sql)
            return sql[pos:end]
    raise AssertionError(f"No section found for role {role!r}")


def test_omega_refinement_has_data_catalog():
    section = _role_section(MIGRATION.read_text(encoding="utf-8"), "omega_refinement")
    assert "data_catalog" in section, (
        "omega_refinement section is missing data_catalog. Refinement "
        "writes silver-layer catalog metadata to this table."
    )


def test_omega_workspace_session_access_is_replaced_by_auth_boundary():
    sql = IDENTITY_BOUNDARY_MIGRATION.read_text(encoding="utf-8")
    assert "REVOKE ALL ON public.user_sessions, public.refresh_tokens" in sql
    assert "FROM PUBLIC, omega_console, omega_workspace" in sql
    assert "omega_auth_resolve_workspace_session" in sql
    assert "TO omega_workspace" in sql


def test_omega_workspace_has_user_workspace_roles():
    section = _role_section(MIGRATION.read_text(encoding="utf-8"), "omega_workspace")
    assert "user_workspace_roles" in section, (
        "omega_workspace section is missing user_workspace_roles. Workspace "
        "cannot resolve active workspace context without this grant."
    )


def test_omega_workspace_has_marketplace_entitlements():
    section = MARKETPLACE_MIGRATION.read_text(encoding="utf-8")
    assert "GRANT SELECT ON marketplace_products, tenant_entitlements, cartridge_installations" in section
    assert "TO omega_workspace" in section
    for table in ("marketplace_products", "tenant_entitlements", "cartridge_installations"):
        assert table in section, (
            f"marketplace migration is missing {table}. Workspace cannot "
            "scope purchased cartuchos without this grant."
        )


def test_omega_mcp_infra_has_cartridge_dags():
    section = _role_section(MIGRATION.read_text(encoding="utf-8"), "omega_mcp_infra")
    assert "cartridge_dags" in section, (
        "omega_mcp_infra section is missing cartridge_dags. The "
        "pipeline.dag_get_source MCP tool reads this table to render "
        "the DAG graph in Studio."
    )


def test_vault_entries_still_only_in_omega_vault():
    sql = MIGRATION.read_text(encoding="utf-8")
    grants = re.findall(
        r"GRANT\s+[^;]*?\s+ON\s+vault_entries\s+TO\s+(\w+)\s*;",
        sql, flags=re.IGNORECASE,
    )
    assert grants, "migration must GRANT vault_entries to omega_vault"
    distinct = sorted(set(grants))
    assert distinct == ["omega_vault"], (
        f"vault_entries grants leaked beyond omega_vault: {distinct!r}. "
        f"Banca-grade defense-in-depth: only omega_vault may touch "
        f"vault_entries."
    )
