SELECT
    DATABASE_NAME,
    HOST,
    SERVICE_NAME,
    SQL_PORT,
    ACTIVE_STATUS
FROM SYS_DATABASES.M_SERVICES
WHERE SERVICE_NAME = 'indexserver'
  AND DATABASE_NAME <> 'SYSTEMDB'
ORDER BY DATABASE_NAME;

SELECT DATABASE_NAME FROM SYS.M_DATABASE;
