
CREATE USER <OMEGA_B1_READER> PASSWORD "<PASSWORD_GENERATED_BY_CUSTOMER_IT>" NO FORCE_FIRST_PASSWORD_CHANGE;

ALTER USER <OMEGA_B1_READER> DISABLE PASSWORD LIFETIME;

GRANT SELECT ON SCHEMA "<COMPANY_DB_1>" TO <OMEGA_B1_READER>;
GRANT SELECT ON SCHEMA "<COMPANY_DB_2>" TO <OMEGA_B1_READER>;
GRANT SELECT ON SCHEMA "<COMPANY_DB_3>" TO <OMEGA_B1_READER>;


