SELECT USER_NAME, USER_DEACTIVATED, DEACTIVATION_TIME, PASSWORD_CHANGE_NEEDED,
       LAST_SUCCESSFUL_CONNECT, LAST_INVALID_CONNECT_ATTEMPT, INVALID_CONNECT_ATTEMPTS
FROM SYS.USERS
WHERE USER_NAME = '<OMEGA_B1_READER>';

SELECT GRANTEE, OBJECT_TYPE, SCHEMA_NAME, OBJECT_NAME, PRIVILEGE, IS_GRANTABLE, GRANTOR
FROM SYS.GRANTED_PRIVILEGES
WHERE GRANTEE = '<OMEGA_B1_READER>'
ORDER BY SCHEMA_NAME, PRIVILEGE;

SELECT GRANTEE, ROLE_NAME, GRANTOR
FROM SYS.GRANTED_ROLES
WHERE GRANTEE = '<OMEGA_B1_READER>';

SELECT USER_NAME, GRANTEE, GRANTEE_TYPE, OBJECT_TYPE, SCHEMA_NAME, OBJECT_NAME, PRIVILEGE, IS_VALID
FROM SYS.EFFECTIVE_PRIVILEGES
WHERE USER_NAME = '<OMEGA_B1_READER>'
  AND (OBJECT_TYPE = 'SYSTEMPRIVILEGE'
       OR PRIVILEGE IN ('INSERT', 'UPDATE', 'DELETE', 'ALTER', 'DROP', 'EXECUTE', 'CREATE ANY', 'DEBUG')
       OR SCHEMA_NAME IN ('<COMPANY_DB_1>', '<COMPANY_DB_2>', '<COMPANY_DB_3>'))
ORDER BY OBJECT_TYPE, SCHEMA_NAME, PRIVILEGE;

SELECT "Version" FROM "<COMPANY_DB_1>"."CINF";
SELECT "Version" FROM "<COMPANY_DB_2>"."CINF";
SELECT "Version" FROM "<COMPANY_DB_3>"."CINF";

