
REVOKE SELECT ON SCHEMA "<COMPANY_DB_1>" FROM <OMEGA_B1_READER>;
REVOKE SELECT ON SCHEMA "<COMPANY_DB_2>" FROM <OMEGA_B1_READER>;
REVOKE SELECT ON SCHEMA "<COMPANY_DB_3>" FROM <OMEGA_B1_READER>;

DROP USER <OMEGA_B1_READER> CASCADE;

