"""Sprint v1.41.1 — Request correlation IDs.

Adds X-Request-ID header to every request/response. Generates one
if the client didn't provide it. Stored in request.state and exposed
to structured logs via contextvars (used by logging_config.JSONFormatter).

v1.42.1 — switched from ``BaseHTTPMiddleware`` to a pure-ASGI middleware
so the header lands on *every* response, including those generated by
upstream exception handlers (FastAPI's HTTPException handler, Starlette's
ServerErrorMiddleware). The old streaming-Response pattern lost the
header whenever an inner middleware short-circuited with a 401/403.
"""
from __future__ import annotations

import contextvars
import logging
import uuid

from starlette.datastructures import State


_log = logging.getLogger(__name__)


request_id_var: contextvars.ContextVar[str | None] = contextvars.ContextVar(
    "request_id", default=None
)


class RequestIDMiddleware:
    """ASGI middleware that stamps an ``X-Request-ID`` header on every
    HTTP response (and WebSocket accept) regardless of which inner
    layer produced it. Intercepts at the ``send`` level — the lowest
    point where headers are still mutable — so 401s emitted by an auth
    dependency, 500s emitted by ``ServerErrorMiddleware`` and successful
    200s all flow through the same injection path.

    Must be registered LAST via ``app.add_middleware`` so it ends up as
    the outermost wrapper in Starlette's middleware stack.
    """

    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        if scope["type"] not in ("http", "websocket"):
            await self.app(scope, receive, send)
            return

        # Pick the client-supplied X-Request-ID if any, else mint a UUID4.
        incoming = ""
        for name, value in scope.get("headers", []) or []:
            if name == b"x-request-id":
                incoming = value.decode("latin1", errors="replace")
                break
        rid = incoming or str(uuid.uuid4())
        rid_bytes = rid.encode("latin1")

        # Expose via contextvar (for structured logs) and request.state
        # (for handlers that prefer the explicit attribute).
        token = request_id_var.set(rid)
        if "state" not in scope:
            scope["state"] = State()
        try:
            scope["state"].request_id = rid
        except Exception:
            # Some Starlette versions keep scope["state"] as a plain
            # dict — fall back to that without crashing.
            pass

        response_started = False

        async def send_wrapper(message):
            nonlocal response_started
            mtype = message.get("type")
            if mtype in ("http.response.start", "websocket.accept"):
                if mtype == "http.response.start":
                    response_started = True
                # Strip any duplicate header an inner layer might have
                # set, then append ours so it always wins.
                headers = [
                    (k, v) for (k, v) in message.get("headers", []) or []
                    if k.lower() != b"x-request-id"
                ]
                headers.append((b"x-request-id", rid_bytes))
                message["headers"] = headers
            await send(message)

        try:
            await self.app(scope, receive, send_wrapper)
        except Exception:
            # Downstream raised before producing a response. The
            # outer ``ServerErrorMiddleware`` would normally build a
            # 500 here, but it doesn't see our ``send_wrapper`` so
            # the header would be lost. Synthesise the 500 ourselves
            # with the rid attached, then swallow — we've already
            # logged the traceback for the operator.
            _log.exception(
                "unhandled exception during request",
                extra={"request_id": rid},
            )
            if scope["type"] == "http" and not response_started:
                await send({
                    "type": "http.response.start",
                    "status": 500,
                    "headers": [
                        (b"content-type", b"application/json"),
                        (b"x-request-id", rid_bytes),
                    ],
                })
                await send({
                    "type": "http.response.body",
                    "body": b'{"detail":"internal error"}',
                })
            # If the response had already started before the exception,
            # the headers are locked in and there's nothing further the
            # middleware can do — fall through silently.
        finally:
            request_id_var.reset(token)
