#!/usr/bin/env bash
set -Eeuo pipefail
set +x
umask 077

if [[ "$#" -ne 5 ]]; then
  echo "Usage: preflight-release-images.sh <ghcr-owner> <immutable-tag> <exact-revision> <exact-version> <absolute-lock-file>" >&2
  exit 2
fi
if [[ "${OMEGA_GHCR_AUTH_ACTIVE:-0}" != "1" ]]; then
  echo "ERROR: run this preflight through ghcr-auth-run.sh." >&2
  exit 3
fi
if [[ -z "${DOCKER_CONFIG:-}" || ! -s "${DOCKER_CONFIG}/config.json" ]]; then
  echo "ERROR: GHCR Docker authentication context is missing." >&2
  exit 3
fi

owner="$1"
image_tag="$2"
target_revision="$3"
target_version="$4"
lock_file="$5"
canonical_source="https://github.com/emmanuelnavaromero02-commits/CONSOLA-V1"
if [[ "$owner" != "emmanuelnavaromero02-commits" ]]; then
  echo "ERROR: GHCR owner differs from the canonical private namespace." >&2
  exit 4
fi
if [[ ! "$target_revision" =~ ^[0-9a-f]{40}$ ]]; then
  echo "ERROR: image revision must be one exact lowercase commit SHA." >&2
  exit 5
fi
if [[ ! "$target_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z][0-9A-Za-z.-]*)?$ ]]; then
  echo "ERROR: expected image version is invalid." >&2
  exit 5
fi
if [[ "$image_tag" != "candidate-${target_revision}" && "$image_tag" != "v${target_version}" ]]; then
  echo "ERROR: image tag must be the exact candidate SHA or immutable release version." >&2
  exit 5
fi
if [[ "${OMEGA_GHCR_PRIVATE_PACKAGES_VERIFIED:-0}" != "1" ]]; then
  echo "ERROR: private GHCR package metadata was not verified." >&2
  exit 3
fi
if [[ "$lock_file" != /* || -e "$lock_file" || -L "$lock_file" ]]; then
  echo "ERROR: lock file must be a new absolute, non-symlink path." >&2
  exit 6
fi
lock_dir="$(dirname -- "$lock_file")"
if [[ ! -d "$lock_dir" || ! -w "$lock_dir" ]]; then
  echo "ERROR: lock file directory must already exist and be writable." >&2
  exit 6
fi

docker_root="/var/lib/docker"
if [[ "${OMEGA_GHCR_PREFLIGHT_TEST_MODE:-0}" == "1" ]]; then
  docker_root="${OMEGA_GHCR_PREFLIGHT_TEST_DOCKER_ROOT:?test Docker root is required}"
fi
if [[ ! -d "$docker_root" || -L "$docker_root" ]]; then
  echo "ERROR: canonical Docker storage root is unavailable." >&2
  exit 6
fi
disk_available() {
  df --output=avail -B1 "$docker_root" | awk 'NR == 2 && $1 ~ /^[0-9]+$/ {print $1}'
}
initial_free="$(disk_available)"
minimum_initial_free=$((30 * 1024 * 1024 * 1024))
minimum_reserve=$((10 * 1024 * 1024 * 1024))
if [[ ! "$initial_free" =~ ^[0-9]+$ || "$initial_free" -lt "$minimum_initial_free" ]]; then
  echo "ERROR: Docker storage headroom is below the 30 GiB pre-pull gate." >&2
  exit 6
fi

image_names=(
  airflow
  banxico
  console
  hubspot
  inegi
  mcp-infra
  refinement
  replicon
  salesforce
  sap_hcm
  sap_s4hana
  sap_successfactors
  sec_edgar
  vault
  workspace
)
lock_names=(
  OMEGA_GCP_IMAGE_AIRFLOW
  OMEGA_GCP_IMAGE_BANXICO
  OMEGA_GCP_IMAGE_CONSOLE
  OMEGA_GCP_IMAGE_HUBSPOT
  OMEGA_GCP_IMAGE_INEGI
  OMEGA_GCP_IMAGE_MCP_INFRA
  OMEGA_GCP_IMAGE_REFINEMENT
  OMEGA_GCP_IMAGE_REPLICON
  OMEGA_GCP_IMAGE_SALESFORCE
  OMEGA_GCP_IMAGE_SAP_HCM
  OMEGA_GCP_IMAGE_SAP_S4HANA
  OMEGA_GCP_IMAGE_SAP_SUCCESSFACTORS
  OMEGA_GCP_IMAGE_SEC_EDGAR
  OMEGA_GCP_IMAGE_VAULT
  OMEGA_GCP_IMAGE_WORKSPACE
)
if [[ "${#image_names[@]}" -ne 15 || "${#lock_names[@]}" -ne 15 ]]; then
  echo "ERROR: release image inventory must contain exactly 15 images." >&2
  exit 7
fi

temp_lock="$(mktemp "${lock_dir%/}/.omega-gcp-image-lock.XXXXXX")"
pull_error="$(mktemp "${lock_dir%/}/.omega-gcp-image-pull.XXXXXX")"
chmod 600 "$temp_lock" "$pull_error"
cleanup() {
  local status=$?
  trap - EXIT
  [[ -z "$temp_lock" ]] || rm -f -- "$temp_lock"
  [[ -z "$pull_error" ]] || rm -f -- "$pull_error"
  exit "$status"
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM
trap 'exit 129' HUP

printf '# Generated by preflight-release-images.sh; contains image references only.\n' > "$temp_lock"
for index in "${!image_names[@]}"; do
  image_name="${image_names[$index]}"
  lock_name="${lock_names[$index]}"
  repository="ghcr.io/${owner}/${image_name}"
  reference="${repository}:${image_tag}"
  : > "$pull_error"
  if ! docker pull --quiet "$reference" >/dev/null 2>"$pull_error"; then
    echo "ERROR: release image pull failed for ${image_name}; inventory is less than 15/15." >&2
    exit 8
  fi
  if ! repo_digests="$(docker image inspect --format '{{json .RepoDigests}}' "$reference" 2>/dev/null)"; then
    echo "ERROR: pulled image has no inspectable digest for ${image_name}." >&2
    exit 9
  fi
  oci_identity="$(docker image inspect --format '{{index .Config.Labels "org.opencontainers.image.revision"}}{{println}}{{index .Config.Labels "org.opencontainers.image.version"}}{{println}}{{index .Config.Labels "org.opencontainers.image.source"}}' "$reference" 2>/dev/null || true)"
  revision="$(sed -n '1p' <<<"$oci_identity")"
  version="$(sed -n '2p' <<<"$oci_identity")"
  source="$(sed -n '3p' <<<"$oci_identity")"
  if [[ "$revision" != "$target_revision" || "$version" != "$target_version" || \
        "$source" != "$canonical_source" ]]; then
    echo "ERROR: OCI source/version/revision identity differs for ${image_name}." >&2
    exit 9
  fi
  if ! digest="$(
    printf '%s' "$repo_digests" | python3 -c '
import json
import re
import sys

repository = sys.argv[1]
try:
    values = json.load(sys.stdin)
except (json.JSONDecodeError, UnicodeDecodeError):
    raise SystemExit(1)
matches = []
for value in values if isinstance(values, list) else []:
    if not isinstance(value, str) or "@" not in value:
        continue
    name, digest = value.rsplit("@", 1)
    if name == repository and re.fullmatch(r"sha256:[0-9a-f]{64}", digest):
        matches.append(digest)
if len(set(matches)) != 1:
    raise SystemExit(1)
sys.stdout.write(matches[0])
' "$repository"
  )"; then
    echo "ERROR: pulled image digest is missing or ambiguous for ${image_name}." >&2
    exit 9
  fi
  printf '%s=%s:%s@%s\n' "$lock_name" "$repository" "$image_tag" "$digest" >> "$temp_lock"
  printf 'GCP_RELEASE_IMAGE\t%s\tPASS\t%s@%s\n' "$image_name" "$image_tag" "$digest"
done

final_free="$(disk_available)"
if [[ ! "$final_free" =~ ^[0-9]+$ || "$final_free" -lt "$minimum_reserve" ]]; then
  echo "ERROR: Docker storage reserve fell below 10 GiB after authenticated pulls." >&2
  exit 9
fi

chmod 600 "$temp_lock"
mv -f -- "$temp_lock" "$lock_file"
temp_lock=""
python3 - "$lock_dir" <<'PY'
import os, sys
fd = os.open(sys.argv[1], os.O_RDONLY | os.O_DIRECTORY)
try: os.fsync(fd)
finally: os.close(fd)
PY
printf 'GCP_RELEASE_IMAGES\tPASS\t15/15\tprivate=3/3\ttag=%s\tlock=%s\n' "$image_tag" "$lock_file"
