#!/usr/bin/env bash
set -Eeuo pipefail
set +x
umask 077

if [[ "$#" -ne 3 ]]; then
  echo "Usage: preflight-release-images.sh <ghcr-owner> <immutable-tag> <absolute-lock-file>" >&2
  exit 2
fi
if [[ "${OMEGA_GHCR_AUTH_ACTIVE:-0}" != "1" ]]; then
  echo "ERROR: run this preflight through ghcr-auth-run.sh." >&2
  exit 3
fi
if [[ -z "${DOCKER_CONFIG:-}" || ! -s "${DOCKER_CONFIG}/config.json" ]]; then
  echo "ERROR: GHCR Docker authentication context is missing." >&2
  exit 3
fi

owner="$1"
image_tag="$2"
lock_file="$3"
if [[ ! "$owner" =~ ^[a-z0-9]([a-z0-9-]{0,37}[a-z0-9])?$ ]]; then
  echo "ERROR: GHCR owner is invalid or is not normalized to lowercase." >&2
  exit 4
fi
if [[ ! "$image_tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z][0-9A-Za-z.-]*)?$ ]]; then
  echo "ERROR: image tag must be an explicit immutable release tag." >&2
  exit 5
fi
if [[ "$lock_file" != /* || -L "$lock_file" ]]; then
  echo "ERROR: lock file must be an absolute, non-symlink path." >&2
  exit 6
fi
lock_dir="$(dirname -- "$lock_file")"
if [[ ! -d "$lock_dir" || ! -w "$lock_dir" ]]; then
  echo "ERROR: lock file directory must already exist and be writable." >&2
  exit 6
fi

image_names=(
  airflow
  banxico
  console
  hubspot
  inegi
  mcp-infra
  refinement
  replicon
  salesforce
  sap_hcm
  sap_s4hana
  sap_successfactors
  sec_edgar
  vault
  workspace
)
lock_names=(
  OMEGA_GCP_IMAGE_AIRFLOW
  OMEGA_GCP_IMAGE_BANXICO
  OMEGA_GCP_IMAGE_CONSOLE
  OMEGA_GCP_IMAGE_HUBSPOT
  OMEGA_GCP_IMAGE_INEGI
  OMEGA_GCP_IMAGE_MCP_INFRA
  OMEGA_GCP_IMAGE_REFINEMENT
  OMEGA_GCP_IMAGE_REPLICON
  OMEGA_GCP_IMAGE_SALESFORCE
  OMEGA_GCP_IMAGE_SAP_HCM
  OMEGA_GCP_IMAGE_SAP_S4HANA
  OMEGA_GCP_IMAGE_SAP_SUCCESSFACTORS
  OMEGA_GCP_IMAGE_SEC_EDGAR
  OMEGA_GCP_IMAGE_VAULT
  OMEGA_GCP_IMAGE_WORKSPACE
)
if [[ "${#image_names[@]}" -ne 15 || "${#lock_names[@]}" -ne 15 ]]; then
  echo "ERROR: release image inventory must contain exactly 15 images." >&2
  exit 7
fi

temp_lock="$(mktemp "${lock_dir%/}/.omega-gcp-image-lock.XXXXXX")"
pull_error="$(mktemp "${lock_dir%/}/.omega-gcp-image-pull.XXXXXX")"
chmod 600 "$temp_lock" "$pull_error"
cleanup() {
  local status=$?
  trap - EXIT
  [[ -z "$temp_lock" ]] || rm -f -- "$temp_lock"
  [[ -z "$pull_error" ]] || rm -f -- "$pull_error"
  exit "$status"
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM
trap 'exit 129' HUP

printf '# Generated by preflight-release-images.sh; contains image references only.\n' > "$temp_lock"
for index in "${!image_names[@]}"; do
  image_name="${image_names[$index]}"
  lock_name="${lock_names[$index]}"
  repository="ghcr.io/${owner}/${image_name}"
  reference="${repository}:${image_tag}"
  : > "$pull_error"
  if ! docker pull --quiet "$reference" >/dev/null 2>"$pull_error"; then
    echo "ERROR: release image pull failed for ${image_name}; inventory is less than 15/15." >&2
    exit 8
  fi
  if ! repo_digests="$(docker image inspect --format '{{json .RepoDigests}}' "$reference" 2>/dev/null)"; then
    echo "ERROR: pulled image has no inspectable digest for ${image_name}." >&2
    exit 9
  fi
  if ! digest="$(
    printf '%s' "$repo_digests" | python3 -c '
import json
import re
import sys

repository = sys.argv[1]
try:
    values = json.load(sys.stdin)
except (json.JSONDecodeError, UnicodeDecodeError):
    raise SystemExit(1)
matches = []
for value in values if isinstance(values, list) else []:
    if not isinstance(value, str) or "@" not in value:
        continue
    name, digest = value.rsplit("@", 1)
    if name == repository and re.fullmatch(r"sha256:[0-9a-f]{64}", digest):
        matches.append(digest)
if len(set(matches)) != 1:
    raise SystemExit(1)
sys.stdout.write(matches[0])
' "$repository"
  )"; then
    echo "ERROR: pulled image digest is missing or ambiguous for ${image_name}." >&2
    exit 9
  fi
  printf '%s=%s:%s@%s\n' "$lock_name" "$repository" "$image_tag" "$digest" >> "$temp_lock"
  printf 'GCP_RELEASE_IMAGE\t%s\tPASS\t%s@%s\n' "$image_name" "$image_tag" "$digest"
done

chmod 600 "$temp_lock"
mv -f -- "$temp_lock" "$lock_file"
temp_lock=""
printf 'GCP_RELEASE_IMAGES\tPASS\t15/15\ttag=%s\tlock=%s\n' "$image_tag" "$lock_file"
