
entities:
  count: 3
  items:
    - name: EmpJob
      description: "Employee Job Information"
    - name: User
      description: "User Core Information"
    - name: PerPerson
      description: "Personal Information"
