from __future__ import annotations


def _permission(
    key: str, label: str, category: str, description: str
) -> dict[str, str]:
    return {
        "key": key,
        "label": label,
        "category": category,
        "description": description,
    }


# fmt: off
PERMISSIONS = [
    _permission("iam.users.read", "Read users", "IAM", "List IAM users and account state."),
    _permission("iam.users.write", "Write users", "IAM", "Create, update, disable and reset users."),
    _permission("iam.roles.read", "Read roles", "IAM", "View roles and permissions."),
    _permission("iam.roles.write", "Write roles", "IAM", "Change role policy definitions."),
    _permission("iam.policies.read", "Read policies", "IAM", "View security policies and lifetimes."),
    _permission("iam.policies.write", "Write policies", "IAM", "Change IAM policies."),
    _permission("security.audit.read", "Read audit", "Security", "View audit events."),
    _permission("security.sessions.read", "Read sessions", "Security", "View active sessions."),
    _permission("security.sessions.revoke", "Revoke sessions", "Security", "Revoke active sessions."),
    _permission("security.login_attempts.read", "Read login attempts", "Security", "View login attempts."),
    _permission("vault.connections.read", "Read vault connections", "Vault", "List masked connection metadata."),
    _permission("vault.connections.write", "Write vault connections", "Vault", "Create/update/delete connection metadata."),
    _permission("vault.secrets.read_masked", "Read masked secrets", "Vault", "List masked secret metadata."),
    _permission("vault.secrets.reveal", "Reveal secrets", "Vault", "Reveal secret values."),
    _permission("datasets.read", "Read datasets", "Data", "Read dataset metadata and data."),
    _permission("datasets.write", "Write datasets", "Data", "Create or refresh datasets."),
    _permission("datasets.delete", "Delete datasets", "Data", "Delete datasets."),
    _permission("pipelines.read", "Read pipelines", "Pipelines", "View pipelines and runs."),
    _permission("pipelines.run", "Run pipelines", "Pipelines", "Trigger pipeline runs."),
    _permission("pipelines.write", "Write pipelines", "Pipelines", "Modify pipeline configuration."),
    _permission("studio.read", "Read studio", "Studio", "View Studio resources."),
    _permission("studio.write", "Write studio", "Studio", "Modify Studio resources."),
    _permission("monitor.read", "Read monitor", "Monitor", "View monitor pages and job state."),
    _permission("workspace.access", "Access workspace", "Workspace", "Access workspace apps."),
    _permission("control_room.write", "Operate control room", "Workspace", "Create, dismiss and reopen OMEGA control-room items."),
    _permission("control_room.approve", "Approve control room actions", "Workspace", "Approve a separately initiated internal Control Room action."),
    _permission("control_room.execute", "Execute control room write-back", "Workspace", "Run explicitly approved Control Room write-back adapters."),
    _permission("mcp.registry.read", "Read MCP registry", "MCP", "View registered MCP services."),
    _permission("mcp.invoke", "Invoke MCP", "MCP", "Invoke MCP tools."),
    _permission("agents.read", "Read agents", "Agents", "View workspace-visible agents and their runs."),
    _permission("agents.write", "Write agents", "Agents", "Create and edit workspace-scoped agents."),
    _permission("agents.execute", "Execute agents", "Agents", "Invoke workspace-visible agents."),
    _permission("apps.read", "Read apps", "Apps", "View analytic apps."),
    _permission("apps.write", "Write apps", "Apps", "Modify analytic apps."),
    _permission("settings.read", "Read settings", "Settings", "View system settings (masked secrets)."),
    _permission("settings.write", "Write settings", "Settings", "Edit/reveal/rotate system settings."),
    _permission("operations.read", "Read operations", "Operations", "View system migrations and service health."),
    _permission("operations.write", "Write operations", "Operations", "Trigger operational actions."),
    _permission("llm.keys.read", "Read workspace LLM key status", "Copilot", "Check whether the workspace has its own LLM provider key configured."),
    _permission("llm.keys.write", "Write workspace LLM key", "Copilot", "Set or rotate the workspace-scoped LLM provider key."),
    _permission("cartridges.read", "Read cartridges", "Cartridges", "List cartridges, view entities and watermarks."),
    _permission("cartridges.write", "Configure cartridges", "Cartridges", "Edit connection metadata and run test_connection probes."),
    _permission("cartridges.execute", "Run cartridge extractions", "Cartridges", "Trigger entity extractions and knowledge-bit runs."),
    _permission("marketplace.read", "Read marketplace", "Marketplace", "View available cartridges and installation status."),
    _permission("marketplace.request", "Request marketplace products", "Marketplace", "Request activation of cartridge products for a workspace."),
    _permission("marketplace.write", "Legacy marketplace write", "Marketplace", "Backward-compatible marketplace write permission."),
    _permission("marketplace.admin", "Administer marketplace products", "Marketplace", "Approve, pause, revoke and reactivate cartridge entitlements."),
    _permission("copilot.use", "Use the copilot", "Copilot", "Open the chat and invoke read-only tools."),
    _permission("copilot.write", "Copilot writes", "Copilot", "Allow the copilot to invoke write-level tools on the user's behalf."),
    _permission("copilot.execute", "Copilot destructive actions", "Copilot", "Allow destructive tool calls — always behind a user-approval card."),
]
# fmt: on

PERMISSION_KEYS = {item["key"] for item in PERMISSIONS}

RESOURCE_ACTION_PERMISSIONS = {
    ("/iam", "read"): "iam.users.read",
    ("/security", "read"): "security.audit.read",
    ("/security/audit", "read"): "security.audit.read",
    ("/security/sessions", "read"): "security.sessions.read",
    ("/security/sessions", "revoke"): "security.sessions.revoke",
    ("/security/permissions", "read"): "iam.roles.read",
    ("/security/login-attempts", "read"): "security.login_attempts.read",
    ("/api/admin/users", "read"): "iam.users.read",
    ("/api/admin/users", "write"): "iam.users.write",
    ("/viewer/vault", "read"): "monitor.read",
    ("/api/vault/connections/replicon", "read"): "vault.connections.read",
    ("/api/vault/connections/replicon", "write"): "vault.connections.write",
    ("/api/vault/secrets/replicon", "read"): "vault.secrets.read_masked",
    ("/api/vault/secrets/replicon", "reveal"): "vault.secrets.reveal",
    ("/api/vault/connections/hubspot", "read"): "vault.connections.read",
    ("/api/vault/connections/hubspot", "write"): "vault.connections.write",
    ("/api/vault/secrets/hubspot", "read"): "vault.secrets.read_masked",
    ("/api/vault/secrets/hubspot", "reveal"): "vault.secrets.reveal",
    ("/api/pipeline", "read"): "pipelines.read",
    ("/api/pipeline/run", "run"): "pipelines.run",
    ("/datasets", "read"): "datasets.read",
    ("/api/datasets", "write"): "datasets.write",
    ("/api/datasets", "delete"): "datasets.delete",
    ("/studio", "read"): "studio.read",
    ("/studio", "write"): "studio.write",
    ("/monitor", "read"): "monitor.read",
    ("/workspace", "access"): "workspace.access",
    ("/agents", "read"): "agents.read",
    ("/api/agents", "read"): "agents.read",
    ("/api/agents", "write"): "agents.write",
    ("/api/agents", "execute"): "agents.execute",
    ("/copilot/tokens", "read"): "copilot.use",
    ("/api/copilot/llm-key", "read"): "llm.keys.read",
    ("/api/copilot/llm-key", "write"): "llm.keys.write",
    ("/marketplace", "read"): "marketplace.read",
    ("/marketplace", "request"): "marketplace.request",
    ("/admin/installations", "read"): "marketplace.admin",
    ("/admin/installations", "write"): "marketplace.admin",
}
