#!/usr/bin/env python3
"""Generate the forward-only SuccessFactors packaged-app reconciliation.

Migration 87 has executed in canonical GCP and is immutable database history.
The current reviewed HTML therefore travels in a new guarded migration.  This
generator makes that migration an exact projection of the packaged HTML and
metadata instead of editing or reverting historical bytes.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SEED = ROOT / "infra" / "init" / "87_sap_successfactors_apps_seed.sql"
FORWARD = ROOT / "infra" / "init" / "99zzv_sap_successfactors_apps_secure_refresh.sql"
APPS = ROOT / "cartridges" / "sap_successfactors" / "apps"
EXPECTED_SHA256 = "bbd5407ca36c32aa8efd6e4c8d94190d4fd80ea5c867e831a88f54a40887845d"
APP_NAMES = (
    "sap_successfactors_talent_health",
    "sap_successfactors_workforce_overview",
)
CHART_SOURCE = "https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"
CHART_INTEGRITY = (
    "sha384-9nhczxUqK87bcKHh20fSQcTGD4qq5GhayNYSYWqwBkINBhOfQLg/" "P5HG5lF1urn4"
)
EXPECTED_METADATA_KEYS = {"name", "title", "description", "datasets_used"}


def _sha256(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def _sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _load_app(name: str) -> tuple[dict[str, Any], str, str]:
    html_path = APPS / f"{name}.html"
    metadata_path = APPS / f"{name}.json"
    try:
        html_raw = html_path.read_bytes()
        metadata_raw = metadata_path.read_bytes()
        html = html_raw.decode("utf-8", errors="strict")
        metadata = json.loads(metadata_raw.decode("utf-8", errors="strict"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise SystemExit(f"cannot load reviewed packaged app {name}: {exc}")
    if not isinstance(metadata, dict) or set(metadata) != EXPECTED_METADATA_KEYS:
        raise SystemExit(f"packaged metadata keys are not exact: {name}")
    if metadata.get("name") != name:
        raise SystemExit(f"packaged metadata name differs: {name}")
    for field in ("title", "description"):
        if not isinstance(metadata.get(field), str) or not metadata[field].strip():
            raise SystemExit(f"packaged metadata {field} is invalid: {name}")
    datasets = metadata.get("datasets_used")
    if (
        not isinstance(datasets, list)
        or not datasets
        or any(
            not isinstance(dataset, str)
            or not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", dataset)
            for dataset in datasets
        )
        or len(set(datasets)) != len(datasets)
    ):
        raise SystemExit(f"packaged dataset inventory is invalid: {name}")
    metadata["datasets_used"] = sorted(datasets)
    if not html_raw.endswith(b"\n") or b"\x00" in html_raw:
        raise SystemExit(f"packaged HTML byte contract differs: {name}")
    if html.count(f'src="{CHART_SOURCE}"') != 1:
        raise SystemExit(f"Chart.js source is not exactly pinned: {name}")
    if html.count(f'integrity="{CHART_INTEGRITY}"') != 1:
        raise SystemExit(f"Chart.js SRI is not exact: {name}")
    if html.count('crossorigin="anonymous"') != 1:
        raise SystemExit(f"Chart.js crossorigin contract differs: {name}")
    if re.search(r"\bon[a-z]+\s*=", html, flags=re.IGNORECASE):
        raise SystemExit(f"packaged HTML contains an inline event handler: {name}")
    delimiter = f"$omega_{name}$"
    if delimiter in html:
        raise SystemExit(f"packaged HTML conflicts with SQL delimiter: {name}")
    return metadata, html, _sha256(html_raw)


def render_forward_migration() -> str:
    apps = [_load_app(name) for name in APP_NAMES]
    lines = [
        "-- GENERATED FILE — do not edit by hand.",
        "--",
        "-- Forward-only reconciliation for immutable migration 87. Generated by",
        "-- scripts/generate_successfactors_apps_seed.py from the reviewed packaged",
        "-- HTML and metadata. The guarded migration runner records these bytes.",
        "",
        "DO $omega_successfactors_owner_preflight$",
        "BEGIN",
        "    IF EXISTS (",
        "        SELECT 1 FROM public.analytic_apps",
        "         WHERE name IN ('sap_successfactors_talent_health',",
        "                        'sap_successfactors_workforce_overview')",
        "           AND created_by_id IS NOT NULL",
        "    ) THEN",
        "        RAISE EXCEPTION 'packaged SuccessFactors app name is user-owned'",
        "            USING ERRCODE = '42501';",
        "    END IF;",
        "END",
        "$omega_successfactors_owner_preflight$;",
        "",
    ]
    for metadata, html, _html_sha256 in apps:
        name = metadata["name"]
        delimiter = f"$omega_{name}$"
        datasets = ", ".join(
            _sql_literal(dataset) for dataset in metadata["datasets_used"]
        )
        lines.extend(
            [
                "INSERT INTO public.analytic_apps",
                "    (name, title, html, description, cartridge_id, visibility,",
                "     datasets_used, tenant_id, workspace_id, scope_status, updated_at)",
                "VALUES (",
                f"    {_sql_literal(name)},",
                f"    {_sql_literal(metadata['title'])},",
                f"    {delimiter}{html}{delimiter},",
                f"    {_sql_literal(metadata['description'])},",
                "    'sap_successfactors', 'shared',",
                f"    ARRAY[{datasets}]::text[],",
                "    NULL, NULL, 'platform_template', clock_timestamp()",
                ")",
                "ON CONFLICT (name) DO UPDATE SET",
                "    title = EXCLUDED.title,",
                "    html = EXCLUDED.html,",
                "    description = EXCLUDED.description,",
                "    cartridge_id = EXCLUDED.cartridge_id,",
                "    visibility = EXCLUDED.visibility,",
                "    datasets_used = EXCLUDED.datasets_used,",
                "    tenant_id = NULL,",
                "    workspace_id = NULL,",
                "    scope_status = 'platform_template',",
                "    updated_at = clock_timestamp();",
                "",
            ]
        )

    expected_rows = []
    for metadata, _html, html_sha256 in apps:
        datasets = ", ".join(
            _sql_literal(dataset) for dataset in metadata["datasets_used"]
        )
        expected_rows.append(
            "("
            + ", ".join(
                (
                    _sql_literal(metadata["name"]),
                    _sql_literal(metadata["title"]),
                    _sql_literal(metadata["description"]),
                    _sql_literal(html_sha256),
                    f"ARRAY[{datasets}]::text[]",
                )
            )
            + ")"
        )
    lines.extend(
        [
            "DO $omega_successfactors_secure_refresh$",
            "DECLARE",
            "    mismatched_apps text;",
            "BEGIN",
            "    SELECT string_agg(expected.name, ', ' ORDER BY expected.name)",
            "      INTO mismatched_apps",
            "      FROM (VALUES",
            "        " + ",\n        ".join(expected_rows),
            "      ) AS expected(name, title, description, html_sha256, datasets_used)",
            "      LEFT JOIN public.analytic_apps app ON app.name = expected.name",
            "      LEFT JOIN public.analytic_app_manifests manifest",
            "        ON manifest.app_name = expected.name",
            "       AND manifest.revision = 'active'",
            "       AND manifest.source = 'packaged_manifest'",
            "     WHERE app.name IS NULL",
            "        OR app.title IS DISTINCT FROM expected.title",
            "        OR app.description IS DISTINCT FROM expected.description",
            "        OR app.cartridge_id IS DISTINCT FROM 'sap_successfactors'",
            "        OR app.visibility IS DISTINCT FROM 'shared'",
            "        OR app.datasets_used IS DISTINCT FROM expected.datasets_used",
            "        OR app.tenant_id IS NOT NULL",
            "        OR app.workspace_id IS NOT NULL",
            "        OR app.scope_status IS DISTINCT FROM 'platform_template'",
            "        OR app.created_by_id IS NOT NULL",
            "        OR encode(public.digest(convert_to(app.html, 'UTF8'), 'sha256'), 'hex')",
            "           IS DISTINCT FROM expected.html_sha256",
            "        OR manifest.html_sha256 IS DISTINCT FROM expected.html_sha256;",
            "",
            "    IF mismatched_apps IS NOT NULL THEN",
            "        RAISE EXCEPTION",
            "            'SuccessFactors secure app reconciliation failed: %',",
            "            mismatched_apps;",
            "    END IF;",
            "END",
            "$omega_successfactors_secure_refresh$;",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify migration 87 and the generated forward migration",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="regenerate only the forward migration; never migration 87",
    )
    args = parser.parse_args()
    if args.check and args.write:
        raise SystemExit("--check and --write are mutually exclusive")

    actual = _sha256(SEED.read_bytes())
    if actual != EXPECTED_SHA256:
        raise SystemExit(
            "migration 87 is immutable database history and has changed: "
            f"expected {EXPECTED_SHA256}, got {actual}"
        )
    expected = render_forward_migration().encode("utf-8")
    if args.write:
        FORWARD.write_bytes(expected)
        print(f"generated {FORWARD.relative_to(ROOT)}")
        return 0
    try:
        current = FORWARD.read_bytes()
    except OSError as exc:
        raise SystemExit(f"forward migration is missing: {exc}")
    if current != expected:
        raise SystemExit(
            "forward migration is stale; run "
            "scripts/generate_successfactors_apps_seed.py --write"
        )
    print("migration 87 immutable; forward packaged-app migration byte-exact")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
