#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
APPS_DIR = REPO / "cartridges" / "sap_successfactors" / "apps"
SEED_PATH = REPO / "infra" / "init" / "87_sap_successfactors_apps_seed.sql"

APP_NAMES = (
    "sap_successfactors_workforce_overview",
    "sap_successfactors_talent_health",
)
CARTRIDGE_ID = "sap_successfactors"
VISIBILITY = "shared"
DELIM = "$seed$"

HEADER = """-- 87_sap_successfactors_apps_seed.sql
-- Seeds SAP SuccessFactors analytic apps into analytic_apps.
-- analytic_apps (created in 08_workspace_ownership.sql) has NO workspace_id column:
-- apps are workspace-agnostic and scoped by cartridge_id + visibility + the
-- workspace-scoped datasets they reference (datasets table, migration 82).
-- Mirrors 83_sap_hcm_apps_seed.sql / 85_sap_s4hana_apps_seed.sql. HTML is embedded
-- inline; console seed_packaged_apps.py later reconciles from the source files.
--
-- GENERATED by scripts/generate_successfactors_apps_seed.py — do not edit by hand.
-- Re-run the generator after touching cartridges/sap_successfactors/apps/*.
"""

CONFLICT = """ON CONFLICT (name) DO UPDATE
SET title = EXCLUDED.title,
    html = EXCLUDED.html,
    description = EXCLUDED.description,
    cartridge_id = EXCLUDED.cartridge_id,
    visibility = EXCLUDED.visibility,
    datasets_used = EXCLUDED.datasets_used,
    updated_at = EXCLUDED.updated_at;
"""

TAIL = """INSERT INTO schema_migrations (filename, applied_at)
VALUES ('87_sap_successfactors_apps_seed.sql', NOW())
ON CONFLICT (filename) DO NOTHING;
"""


def _quote(value: str) -> str:
    if DELIM in value:
        raise SystemExit(
            f"value contains the {DELIM} delimiter and cannot be embedded safely"
        )
    return f"{DELIM}{value}{DELIM}"


def _pg_text_array(values: list[str]) -> str:
    for item in values:
        if not item.replace("_", "").isalnum():
            raise SystemExit(f"unexpected dataset name: {item!r}")
    return _quote("{" + ",".join(values) + "}") + "::text[]"


def render() -> str:
    chunks = [HEADER]
    for name in APP_NAMES:
        html = (APPS_DIR / f"{name}.html").read_text(encoding="utf-8")
        sidecar = json.loads((APPS_DIR / f"{name}.json").read_text(encoding="utf-8"))
        if sidecar.get("name") != name:
            raise SystemExit(f"sidecar name mismatch for {name}")
        datasets = list(sidecar.get("datasets_used") or [])
        if not datasets:
            raise SystemExit(f"{name} declares no datasets")
        chunks.append(
            "\nINSERT INTO analytic_apps "
            "(name, title, html, description, cartridge_id, visibility, "
            "datasets_used, updated_at)\n"
            f"VALUES ({_quote(name)}, {_quote(sidecar['title'])}, {_quote(html)}, "
            f"{_quote(sidecar['description'])}, {_quote(CARTRIDGE_ID)}, "
            f"{_quote(VISIBILITY)}, {_pg_text_array(datasets)}, NOW())\n"
            f"{CONFLICT}"
        )
    chunks.append("\n" + TAIL)
    return "".join(chunks)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if out of date")
    args = parser.parse_args()

    rendered = render()
    if args.check:
        current = SEED_PATH.read_text(encoding="utf-8")
        if current != rendered:
            print(
                "87_sap_successfactors_apps_seed.sql is out of date; "
                "run scripts/generate_successfactors_apps_seed.py",
                file=sys.stderr,
            )
            return 1
        print("seed matches cartridge sources")
        return 0

    SEED_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {SEED_PATH.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
