#!/usr/bin/env bash
# v1.0 preflight — run BEFORE `make up` to catch the things that
# silently break a fresh bring-up: no Docker daemon, an occupied port,
# a host Python that cannot generate Fernet-shaped keys via stdlib, or
# an invalid compose file.
#
# Read-only and idempotent: it inspects, never mutates. Exit code is 0
# when the full stack CAN be brought up and non-zero when a hard blocker
# is present, so it is safe to chain:
#
#     bash scripts/preflight.sh && make up
#
# See docs/runbook/09_demo_beta.md for the full flow.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE_FILE="${COMPOSE_FILE:-${ROOT}/infra/docker-compose.yml}"

BLOCKERS=0
WARNINGS=0

ok()    { echo "  ✅ $*"; }
warn()  { echo "  ⚠️  $*"; WARNINGS=$((WARNINGS + 1)); }
block() { echo "  ❌ $*"; BLOCKERS=$((BLOCKERS + 1)); }

echo "OMEGA v1.0 preflight"
echo "════════════════════"

# ── 1. Docker engine + daemon ──────────────────────────────────────────
echo ""
echo "Docker:"
if ! command -v docker >/dev/null 2>&1; then
    block "docker not installed — install Docker Engine 24+ (see docs/runbook/01_arrancar_desde_cero.md)"
elif ! docker info >/dev/null 2>&1; then
    block "docker daemon not reachable. Start Docker Desktop / the docker service. \
On a CI/sandbox without a daemon you cannot run 'make up' — use the unit suites instead (make test)."
else
    ok "docker daemon reachable"
fi

if docker compose version >/dev/null 2>&1; then
    ok "docker compose available ($(docker compose version --short 2>/dev/null || echo 'v2'))"
else
    block "'docker compose' (v2) not available — install the compose plugin"
fi

# ── 2. Compose file validity ───────────────────────────────────────────
echo ""
echo "Compose config:"
if [ ! -f "${COMPOSE_FILE}" ]; then
    block "compose file not found at ${COMPOSE_FILE}"
elif docker compose -f "${COMPOSE_FILE}" config -q >/dev/null 2>&1; then
    ok "docker compose config valid"
else
    # config can fail just because .env is missing; surface that nuance.
    if [ ! -f "${ROOT}/infra/.env" ]; then
        warn "compose config could not be fully validated — infra/.env is missing (generated by 'make up'). Re-run preflight after the first 'make up'."
    else
        block "docker compose config invalid — run: docker compose -f ${COMPOSE_FILE} config"
    fi
fi

# ── 3. infra/.env ──────────────────────────────────────────────────────
echo ""
echo "Secrets / .env:"
if [ -f "${ROOT}/infra/.env" ]; then
    ok "infra/.env present"
else
    warn "infra/.env absent — 'make up' runs infra/bootstrap.sh + bootstrap-keys.sh to generate it. \
infra/.env.example documents every key (incl. BOOTSTRAP_ADMIN_*)."
fi

# ── 4. Host Python Fernet key generation ────────────────────────────────
echo ""
echo "Host Python (used by bootstrap.sh):"
PYBIN="$(command -v python3 || command -v python || true)"
if [ -z "${PYBIN}" ]; then
    block "no host python3 found — bootstrap.sh needs it to generate FIELD_ENCRYPTION_KEY"
elif "${PYBIN}" -c "import base64, os; k=base64.urlsafe_b64encode(os.urandom(32)).decode(); assert len(k) == 44 and k.endswith('=')" >/dev/null 2>&1; then
    ok "python Fernet key generation works ($("${PYBIN}" --version 2>&1))"
else
    block "host python cannot generate Fernet-shaped keys via stdlib base64/os. Fix ${PYBIN} before running 'make up'."
fi

# ── 5. Required host ports free ────────────────────────────────────────
echo ""
echo "Ports (must be free before 'make up'):"
PORTS="8000 8001 8010 8082 8088 8300 8500 9001 8025 8201 8202 8203 8204 15432"
port_in_use() {
    local p="$1"
    if command -v ss >/dev/null 2>&1; then
        ss -ltn 2>/dev/null | grep -qE "[:.]${p}\b"
    elif command -v lsof >/dev/null 2>&1; then
        lsof -iTCP:"${p}" -sTCP:LISTEN >/dev/null 2>&1
    else
        return 2  # no tool to check
    fi
}
PORT_TOOL_MISSING=0
BUSY_PORTS=""
for p in ${PORTS}; do
    if port_in_use "${p}"; then
        rc=0
    else
        rc=$?
    fi
    if [ "${rc}" -eq 0 ]; then
        BUSY_PORTS="${BUSY_PORTS} ${p}"
    elif [ "${rc}" -eq 2 ]; then
        PORT_TOOL_MISSING=1
    fi
done
if [ "${PORT_TOOL_MISSING}" = "1" ]; then
    warn "no ss/lsof to check ports — verify 8000/8001 are free manually"
elif [ -n "${BUSY_PORTS}" ]; then
    block "ports already in use:${BUSY_PORTS} — stop the conflicting process or run 'make down' first"
else
    ok "all required ports free"
fi

# ── URLs the operator will use after 'make up' ─────────────────────────
echo ""
echo "Once the stack is up, the demo surfaces live at:"
echo "  • Console (FastAPI static export):         http://localhost:8000"
echo "  • Control Room (FastAPI backend):          http://localhost:8000/control-room"
echo "  • Backend health (no auth):                http://localhost:8000/healthz"
echo "  • Backend readiness (deps):                http://localhost:8000/readyz"
echo "  • Superset:                                http://localhost:8088"
echo "  • Airflow:                                 http://localhost:8082"
echo "  • SAP cartridges:                          http://localhost:8202-8204/health"
echo "  Local seed login: emmanuel@local.ai / Admin123!  (rotate before real data)"

# ── Verdict ────────────────────────────────────────────────────────────
echo ""
echo "════════════════════"
if [ "${BLOCKERS}" -gt 0 ]; then
    echo "❌ ${BLOCKERS} blocker(s), ${WARNINGS} warning(s). Resolve blockers before 'make up'."
    exit 1
fi
echo "✅ No blockers (${WARNINGS} warning(s)). You can run: make up"
