from __future__ import annotations

from typing import Any


ACTION_TEMPLATES: dict[str, dict[str, Any]] = {
    "restore_data_source": {
        "template_id": "restore_data_source",
        "template_type": "operational_data_recovery",
        "cartridge_id": "platform",
        "surface": "operational_diagnostics",
        "capability": "data_recovery",
        "label": "Restaurar fuente de datos",
        "description": "Valida instalacion, credenciales, materializacion y scope tenant/workspace.",
        "action_kind": "data_recovery",
        "risk_level": "medium",
        "mode_default": "dry_run",
        "requires_approval": True,
        "writeback_contract": "operational_data_recovery",
        "writeback_version": 1,
    },
    "create_followup_task": {
        "template_id": "create_followup_task",
        "template_type": "internal_followup_task",
        "cartridge_id": "platform",
        "surface": "business_experience",
        "capability": "business_workflow",
        "label": "Crear seguimiento operativo",
        "description": "Genera una tarea auditada para responsable operativo.",
        "action_kind": "followup_task",
        "risk_level": "low",
        "mode_default": "dry_run",
        "requires_approval": True,
        "writeback_contract": "decision_actions",
        "writeback_version": 1,
    },
    "create_investigation_note": {
        "template_id": "create_investigation_note",
        "template_type": "internal_investigation_note",
        "cartridge_id": "platform",
        "surface": "business_experience",
        "capability": "business_workflow",
        "label": "Crear nota de investigacion",
        "description": "Registra una nota interna auditada con evidencia del item.",
        "action_kind": "investigation_note",
        "risk_level": "low",
        "mode_default": "dry_run",
        "requires_approval": False,
        "writeback_contract": "control_room_item_events",
        "writeback_version": 1,
    },
    "mark_decision_for_monitoring": {
        "template_id": "mark_decision_for_monitoring",
        "template_type": "internal_decision_monitoring",
        "cartridge_id": "platform",
        "surface": "business_experience",
        "capability": "business_workflow",
        "label": "Marcar decision para monitoreo",
        "description": "Activa seguimiento interno de la decision y sus metricas.",
        "action_kind": "decision_monitoring",
        "risk_level": "low",
        "mode_default": "dry_run",
        "requires_approval": True,
        "writeback_contract": "control_room_item_metadata",
        "writeback_version": 1,
    },
    "request_owner_review": {
        "template_id": "request_owner_review",
        "template_type": "preview_only",
        "cartridge_id": "platform",
        "surface": "business_experience",
        "capability": "business_workflow",
        "label": "Solicitar revision de owner",
        "description": "Prepara solicitud de revision humana con evidencia y SQL.",
        "action_kind": "owner_review",
        "risk_level": "low",
        "mode_default": "dry_run",
        "requires_approval": True,
        "writeback_contract": "preview_only",
        "writeback_version": 1,
    },
    "prepare_replicon_adjustment": {
        "template_id": "prepare_replicon_adjustment",
        "template_type": "prepare_replicon_adjustment",
        "cartridge_id": "replicon",
        "surface": "business_experience",
        "capability": "replicon_writeback",
        "label": "Preparar ajuste Replicon",
        "description": "Construye payload seguro para revisar billing, timesheet o asignacion en Replicon.",
        "action_kind": "replicon_adjustment",
        "risk_level": "high",
        "mode_default": "dry_run",
        "requires_approval": True,
        "writeback_contract": "replicon_adjustment",
        "writeback_version": 1,
    },
    "prepare_billing_review": {
        "template_id": "prepare_billing_review",
        "template_type": "prepare_billing_review",
        "cartridge_id": "replicon",
        "surface": "business_experience",
        "capability": "replicon_writeback",
        "label": "Preparar revision de facturacion",
        "description": "Construye evidencia para validar WIP, margen, horas y facturacion.",
        "action_kind": "billing_review",
        "risk_level": "medium",
        "mode_default": "dry_run",
        "requires_approval": True,
        "writeback_contract": "replicon_billing_review",
        "writeback_version": 1,
    },
    "prepare_sap_review": {
        "template_id": "prepare_sap_review",
        "template_type": "sap_s4hana_http",
        "cartridge_id": "sap_s4hana",
        "surface": "business_experience",
        "capability": "sap_s4hana_writeback",
        "label": "Preparar revision SAP",
        "description": "Construye payload de revision para revenue, backlog, compras o maestro S/4.",
        "action_kind": "sap_review",
        "risk_level": "high",
        "mode_default": "dry_run",
        "requires_approval": True,
        "writeback_contract": "sap_s4hana_review",
        "writeback_version": 1,
    },
    "prepare_s4_revenue_review": {
        "template_id": "prepare_s4_revenue_review",
        "template_type": "sap_s4hana_http",
        "cartridge_id": "sap_s4hana",
        "surface": "business_experience",
        "capability": "sap_s4hana_writeback",
        "label": "Preparar revision comercial S/4",
        "description": "Prepara evidencia de revenue, backlog, pedido y owner comercial.",
        "action_kind": "s4_revenue_review",
        "risk_level": "high",
        "mode_default": "dry_run",
        "requires_approval": True,
        "writeback_contract": "sap_s4hana_revenue_review",
        "writeback_version": 1,
    },
    "prepare_s4_business_partner_review": {
        "template_id": "prepare_s4_business_partner_review",
        "template_type": "sap_s4hana_http",
        "cartridge_id": "sap_s4hana",
        "surface": "business_experience",
        "capability": "sap_s4hana_writeback",
        "label": "Preparar revision de business partner",
        "description": "Prepara evidencia de maestro BP, datos fiscales, direccion y bloqueo preventivo.",
        "action_kind": "s4_business_partner_review",
        "risk_level": "medium",
        "mode_default": "dry_run",
        "requires_approval": True,
        "writeback_contract": "sap_s4hana_business_partner_review",
        "writeback_version": 1,
    },
    "prepare_s4_procurement_review": {
        "template_id": "prepare_s4_procurement_review",
        "template_type": "sap_s4hana_http",
        "cartridge_id": "sap_s4hana",
        "surface": "business_experience",
        "capability": "sap_s4hana_writeback",
        "label": "Preparar revision de compras S/4",
        "description": "Prepara evidencia de proveedor, gasto, contrato y aprobaciones.",
        "action_kind": "s4_procurement_review",
        "risk_level": "medium",
        "mode_default": "dry_run",
        "requires_approval": True,
        "writeback_contract": "sap_s4hana_procurement_review",
        "writeback_version": 1,
    },
    "prepare_hcm_access_review": {
        "template_id": "prepare_hcm_access_review",
        "template_type": "sap_hcm_it0008",
        "cartridge_id": "sap_hcm",
        "surface": "business_experience",
        "capability": "sap_hcm_writeback",
        "label": "Preparar revision HCM acceso/nomina",
        "description": "Prepara baja, bloqueo de usuario, evidencia de posicion y posible cola de nomina.",
        "action_kind": "hcm_access_review",
        "risk_level": "high",
        "mode_default": "dry_run",
        "requires_approval": True,
        "writeback_contract": "sap_hcm_it0008",
        "writeback_version": 1,
    },
    "prepare_hcm_org_review": {
        "template_id": "prepare_hcm_org_review",
        "template_type": "sap_hcm_http",
        "cartridge_id": "sap_hcm",
        "surface": "business_experience",
        "capability": "sap_hcm_writeback",
        "label": "Preparar revision organizacional HCM",
        "description": "Prepara evidencia de centro de costo, posicion, jefe y estructura.",
        "action_kind": "hcm_org_review",
        "risk_level": "medium",
        "mode_default": "dry_run",
        "requires_approval": True,
        "writeback_contract": "sap_hcm_org_review",
        "writeback_version": 1,
    },
    "prepare_successfactors_review": {
        "template_id": "prepare_successfactors_review",
        "template_type": "sap_successfactors_http",
        "cartridge_id": "sap_successfactors",
        "surface": "business_experience",
        "capability": "sap_successfactors_writeback",
        "label": "Preparar revision SuccessFactors",
        "description": "Prepara evidencia de empleado, manager, departamento, job code y aprobador.",
        "action_kind": "successfactors_employee_review",
        "risk_level": "medium",
        "mode_default": "dry_run",
        "requires_approval": True,
        "writeback_contract": "sap_successfactors_employee_review",
        "writeback_version": 1,
    },
    "prepare_successfactors_recruiting_review": {
        "template_id": "prepare_successfactors_recruiting_review",
        "template_type": "sap_successfactors_http",
        "cartridge_id": "sap_successfactors",
        "surface": "business_experience",
        "capability": "sap_successfactors_writeback",
        "label": "Preparar revision recruiting SF",
        "description": "Prepara evidencia de requisicion, vacante, etapa y owner.",
        "action_kind": "successfactors_recruiting_review",
        "risk_level": "medium",
        "mode_default": "dry_run",
        "requires_approval": True,
        "writeback_contract": "sap_successfactors_recruiting_review",
        "writeback_version": 1,
    },
}


__all__ = ("ACTION_TEMPLATES",)
